const handEl=document.getElementById('hand'),playersView=document.getElementById('playersView'),statusEl=document.getElementById('status'),drawBtn=document.getElementById('draw'),discardEl=document.getElementById('discard'),targetsEl=document.getElementById('targets'),futureEl=document.getElementById('future'),playersEl=document.getElementById('players'),defuseDialog=document.getElementById('defuseDialog');let game,timer,sortHand=true;
document.title='Chatastrophe';document.querySelector('h1').textContent='Chatastrophe';
defuseDialog.querySelector('h2').textContent='Protection activée !';defuseDialog.querySelector('p').textContent='L’incident félin retourne dans la pioche. Choisissez sa position.';
document.querySelector('h2').insertAdjacentHTML('beforeend',' <button id="sortHand">Trier la main</button>');const sortHandButton=document.getElementById('sortHand');document.head.insertAdjacentHTML('beforeend','<style>.hand .card{overflow:hidden;background:linear-gradient(145deg,#fff 0 63%,#fda4af 64% 100%);border-width:3px}.hand .card:before{display:block;font-size:26px}.hand .type-attack{background:linear-gradient(145deg,#fff1f2,#ef4444);border-color:#991b1b}.hand .type-attack:before{content:"⚔️"}.hand .type-skip{background:linear-gradient(145deg,#ecfeff,#06b6d4);border-color:#0e7490}.hand .type-skip:before{content:"⏭️"}.hand .type-favor{background:linear-gradient(145deg,#faf5ff,#a855f7);border-color:#6b21a8}.hand .type-favor:before{content:"🎁"}.hand .type-shuffle{background:linear-gradient(145deg,#fff7ed,#f97316);border-color:#9a3412}.hand .type-shuffle:before{content:"🔀"}.hand .type-future{background:linear-gradient(145deg,#eff6ff,#3b82f6);border-color:#1d4ed8}.hand .type-future:before{content:"🔮"}.hand .type-nope{background:linear-gradient(145deg,#e5e7eb,#475569);border-color:#1e293b;color:#fff}.hand .type-nope:before{content:"🚫"}.hand .type-cat{background:linear-gradient(145deg,#fefce8,#eab308);border-color:#a16207}.hand .type-cat:before{content:"🐱"}.hand .type-defuse{background:linear-gradient(145deg,#ecfdf5,#22c55e);border-color:#15803d}.hand .type-defuse:before{content:"🧯"}.hand .card.danger{background:radial-gradient(circle,#fb7185 0 32%,#7f1d1d 33% 100%);color:white}.hand .card.danger:before{content:"💥"}</style>');
const definitions={attack:'Double tour',skip:'Esquive',favor:'Échange forcé',shuffle:'Remous',future:'Prémonition',nope:'Annulation',cat:'Compagnon'};
function shuffle(values){for(let i=values.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[values[i],values[j]]=[values[j],values[i]]}return values}
function makeDeck(){const deck=[];for(const type of ['attack','skip','favor','shuffle','future','nope','cat'])for(let i=0;i<4;i++)deck.push({type});return shuffle(deck)}
function name(index){return index?'Bot '+index:'Vous'}
function cardName(card){return card.type==='kitten'?'💥 Incident félin':card.type==='defuse'?'🧯 Protection':definitions[card.type]}
function log(text){game.log.unshift(text);game.log=game.log.slice(0,7)}
function start(){clearTimeout(timer);const count=Number(playersEl.value);game={deck:makeDeck(),discard:[],people:Array.from({length:count},()=>({hand:[{type:'defuse'}],alive:true,turns:0})),turn:0,pending:null,log:[],over:false,future:[]};game.people.forEach(person=>{for(let i=0;i<7;i++)person.hand.push(game.deck.pop())});game.people[0].turns=1;game.deck.push({type:'defuse'});for(let index=0;index<count-1;index+=1)game.deck.push({type:'kitten'});shuffle(game.deck);statusEl.textContent='Chaque joueur commence avec une Protection ; les incidents félins sont seulement dans la pioche.';render()}
function next(){const alive=game.people.filter(person=>person.alive);if(alive.length===1){game.over=true;statusEl.textContent=`${name(game.people.findIndex(person=>person.alive))} survit et gagne !`;render();return}do{game.turn=(game.turn+1)%game.people.length}while(!game.people[game.turn].alive);game.people[game.turn].turns=Math.max(1,game.people[game.turn].turns);game.pending=null;game.future=[];statusEl.textContent=game.turn?'Le bot prépare son coup.':'Votre tour : jouez puis piochez.';render();if(game.turn)timer=setTimeout(bot,550+Math.random()*650)}
function draw(index){if(index!==game.turn||game.over)return;const person=game.people[index],card=game.deck.pop();if(!card){statusEl.textContent='La pioche est vide.';return}if(card.type!=='kitten'){person.hand.push(card);log(`${name(index)} pioche une carte.`);endDraw(index);return}const defuse=person.hand.findIndex(entry=>entry.type==='defuse');if(defuse<0){person.alive=false;game.discard.push(card);log(`${name(index)} est éliminé par un incident !`);window.GameEffects?.play('error');next();return}person.hand.splice(defuse,1);game.discard.push({type:'defuse'});game.pending={kitten:card,player:index};log(`${name(index)} utilise une Protection.`);if(index===0){defuseDialog.showModal();render()}else{insertKitten(['top','middle','bottom'][Math.floor(Math.random()*3)])}}
function endDraw(index){game.people[index].turns--;if(game.people[index].turns>0){statusEl.textContent=`${name(index)} doit encore jouer ${game.people[index].turns} tour.`;render();if(index)timer=setTimeout(bot,650);return}next()}
function insertKitten(place){const {kitten,player}=game.pending;const index=place==='top'?game.deck.length:place==='bottom'?0:Math.floor(game.deck.length/2);game.deck.splice(index,0,kitten);game.pending=null;defuseDialog.close();endDraw(player)}
function chooseTarget(cardIndex,targetIndex){const pending=game.pending;if(pending?.cats){const person=game.people[0],target=game.people[targetIndex];pending.cats.slice().sort((left,right)=>right-left).forEach(index=>game.discard.push(person.hand.splice(index,1)[0]));const taken=target.hand.splice(Math.floor(Math.random()*target.hand.length),1)[0];if(taken)person.hand.push(taken);log(`${name(targetIndex)} vous donne une carte après votre paire de chats.`);game.pending=null;render();return}game.pending=null;useCard(cardIndex,targetIndex);}
function useCard(cardIndex,targetIndex=null){if(game.turn!==0||game.over)return;const person=game.people[0],card=person.hand[cardIndex];if(!card||card.type==='defuse'||card.type==='kitten')return;if(card.type==='favor'&&targetIndex===null){game.pending={favor:cardIndex};render();return}if(card.type==='cat'&&targetIndex===null){const other=person.hand.findIndex((entry,index)=>index!==cardIndex&&entry.type==='cat');if(other<0){statusEl.textContent='Il faut jouer deux cartes Chat identiques pour voler une carte.';return}game.pending={cats:[cardIndex,other]};render();return}person.hand.splice(cardIndex,1);game.discard.push(card);window.GameEffects?.play('move');if(card.type==='attack'){const target=nextAlive(game.turn);game.people[game.turn].turns=0;game.people[target].turns+=2;log(`Vous attaquez ${name(target)} : ${game.people[target].turns} tours à jouer.`);next();return}if(card.type==='skip'){log('Vous passez une pioche.');endDraw(0);return}if(card.type==='shuffle'){shuffle(game.deck);log('La pioche est mélangée.')}if(card.type==='future'){game.future=game.deck.slice(-3).reverse();log('Vous regardez les trois prochaines cartes.')}if(card.type==='favor'){const target=game.people[targetIndex];const taken=target.hand.splice(Math.floor(Math.random()*target.hand.length),1)[0];if(taken)person.hand.push(taken);log(`${name(targetIndex)} vous donne une carte.`)}render()}
function nextAlive(index){do{index=(index+1)%game.people.length}while(!game.people[index].alive);return index}
function bot(){if(game.turn===0||game.over)return;const person=game.people[game.turn];const safe=person.hand.findIndex(card=>['attack','skip'].includes(card.type)&&person.turns>0);if(safe>=0){const card=person.hand.splice(safe,1)[0];game.discard.push(card);if(card.type==='attack'){const attacker=game.turn,target=nextAlive(attacker);person.turns=0;game.people[target].turns+=2;log(`${name(attacker)} attaque ${name(target)} (${game.people[target].turns} tours).`);next()}else{log(`${name(game.turn)} passe une pioche.`);endDraw(game.turn)}return}if(Math.random()<.2){const shuffleIndex=person.hand.findIndex(card=>card.type==='shuffle');if(shuffleIndex>=0){game.discard.push(person.hand.splice(shuffleIndex,1)[0]);shuffle(game.deck);log(`${name(game.turn)} mélange.`);render();timer=setTimeout(bot,450);return}}draw(game.turn)}
function render(){playersView.innerHTML=game.people.map((person,index)=>`<article class="player${index===game.turn&&!game.over?' active':''}"><strong>${name(index)} ${person.alive?'':'💥'}</strong><br><small>${person.hand.length} carte${person.hand.length>1?'s':''} · ${person.turns||0} tour${person.turns>1?'s':''}</small></article>`).join('');const cards=game.people[0].hand.map((card,index)=>({card,index})).sort((a,b)=>sortHand?cardName(a.card).localeCompare(cardName(b.card)):a.index-b.index);handEl.innerHTML=cards.map(({card,index})=>`<button class="card type-${card.type}${card.type==='kitten'?' danger':''}" data-card="${index}">${cardName(card)}</button>`).join('');handEl.querySelectorAll('[data-card]').forEach(button=>button.onclick=()=>useCard(Number(button.dataset.card)));sortHandButton.textContent=sortHand?'Ordre de pioche':'Trier la main';const targeting=game.pending?.favor!==undefined||game.pending?.cats;targetsEl.innerHTML=targeting?game.people.slice(1).map((person,index)=>person.alive&&person.hand.length?`<button data-target="${index+1}">${game.pending?.cats?'Voler une carte à':'Demander une carte à'} ${name(index+1)}</button>`:'').join(''):'';targetsEl.querySelectorAll('[data-target]').forEach(button=>button.onclick=()=>chooseTarget(game.pending?.favor,Number(button.dataset.target)));drawBtn.disabled=game.turn!==0||game.over||game.pending;drawBtn.textContent=`PIOCHER · ${game.deck.length}`;const top=game.discard.at(-1);discardEl.textContent=top?`Défausse : ${cardName(top)}`:'Défausse vide';futureEl.innerHTML=game.future.length?`<strong>Futur :</strong>${game.future.map(card=>`<span class="card type-${card.type}">${cardName(card)}</span>`).join('')}`:'';document.getElementById('log').innerHTML=game.log.map(entry=>`<li>${entry}</li>`).join('')}
drawBtn.onclick=()=>draw(0);document.getElementById('newGame').onclick=start;playersEl.onchange=start;sortHandButton.onclick=()=>{sortHand=!sortHand;render()};defuseDialog.querySelectorAll('[data-place]').forEach(button=>button.onclick=()=>insertKitten(button.dataset.place));if(!window.GameEffects){const script=document.createElement('script');script.src='../../../shared/effects.js?v=1';document.head.appendChild(script)}localStorage.setItem('game-hub:last-game','chatastrophe');start();
