const table = document.getElementById('table'); const status = document.getElementById('status'); const scores = document.getElementById('scores'); const deckButton = document.getElementById('deck'); const discardButton = document.getElementById('discard'); const discardDrawButton = document.getElementById('discardDraw'); const playersSelect = document.getElementById('players'); const limitSelect = document.getElementById('limit'); const columnsOption = document.getElementById('columns'); const doubleFinishOption = document.getElementById('doubleFinish');
document.title='Grille Zéro';document.querySelector('h1').textContent='Grille Zéro';
document.head.insertAdjacentHTML('beforeend','<style>.card:not(.back){background:linear-gradient(145deg,#fff 0 55%,#d9f99d 56% 100%);box-shadow:inset 0 0 0 3px #f8fafc}.card:not(.back):before{content:"GRILLE";position:absolute;font-size:7px;letter-spacing:1px;top:4px;color:#0f766e}.card{position:relative;overflow:hidden}.card.negative{background:linear-gradient(145deg,#fff 0 55%,#99f6e4 56% 100%)}.card.back{background:repeating-linear-gradient(45deg,#0f766e 0 8px,#d9f99d 8px 16px)!important}</style>');
let game; let botTimer;
function shuffle(values){for(let i=values.length-1;i>0;i-=1){const j=Math.floor(Math.random()*(i+1));[values[i],values[j]]=[values[j],values[i]]}return values}
function makeDeck(){return shuffle([...Array(5).fill(-2),...Array(10).fill(-1),...Array(15).fill(0),...Array.from({length:12},(_,index)=>Array(10).fill(index+1)).flat()])}
function name(i){return i===0?'Vous':`Bot ${i}`}
function log(text){game.log.unshift(text);game.log=game.log.slice(0,8)}
function visible(card){return card && card.up && !card.removed}
function boardScore(player){return player.board.reduce((sum,card)=>sum+(visible(card)?card.value:0),0)}
function allRevealed(player){return player.board.every(card=>card.removed||card.up)}
function drawCard(){if(!game.deck.length){game.deck=shuffle(game.discard.splice(0,game.discard.length-1))}return game.deck.pop()}
function removeColumns(player){if(!columnsOption.checked)return;for(let column=0;column<4;column+=1){const cards=[0,1,2].map(row=>player.board[row*4+column]);if(cards.every(visible)&&cards.every(card=>card.value===cards[0].value)){cards.forEach(card=>{card.removed=true});log(`${name(game.turn)} retire une colonne de ${cards[0].value}.`)}}}
function finishRound(finisher){game.people.forEach(player=>player.board.forEach(card=>{if(!card.removed)card.up=true}));game.people.forEach(removeColumns);const roundScores=game.people.map(boardScore);if(doubleFinishOption.checked&&roundScores[finisher]!==Math.min(...roundScores))roundScores[finisher]*=2;game.people.forEach((player,index)=>player.score+=roundScores[index]);log(`Fin de manche : ${roundScores.map((score,index)=>`${name(index)} ${score}`).join(' · ')}.`);if(game.people.some(player=>player.score>=Number(limitSelect.value))){game.over=true;const winner=game.people.map((player,index)=>({index,score:player.score})).sort((a,b)=>a.score-b.score)[0];status.textContent=`${name(winner.index)} gagne avec ${winner.score} points.`;render();return}game.round+=1;startRound()}
function nextTurn(){const completed=allRevealed(game.people[game.turn]);if(completed&&game.finisher===null){game.finisher=game.turn;log(`${name(game.turn)} révèle sa dernière carte : chaque adversaire joue encore une fois.`)}const nextPlayer=(game.turn+1)%game.people.length;if(game.finisher!==null&&nextPlayer===game.finisher){finishRound(game.finisher);return}game.turn=nextPlayer;game.pending=null;status.textContent=game.turn===0?'À vous de jouer.':`${name(game.turn)} réfléchit.`;render();scheduleBot()}
function replace(index){if(game.turn!==0||!game.pending)return;const player=game.people[0];const old=player.board[index];player.board[index]={value:game.pending.value,up:true,removed:false};if(old&&!old.removed)game.discard.push(old.value);removeColumns(player);log(`Vous remplacez une carte par ${game.pending.value}.`);nextTurn()}
function useDiscard(){if(game.turn!==0||game.pending||!game.discard.length)return;game.pending={value:game.discard.pop(),fromDiscard:true};status.textContent='Choisissez une carte à remplacer.';render()}
function draw(){if(game.turn!==0||game.pending)return;game.pending={value:drawCard(),fromDiscard:false};status.textContent='Remplacez une carte, ou défaussez puis révélez une carte cachée.';render()}
function discardAndReveal(){if(game.turn!==0||!game.pending||game.pending.fromDiscard)return;game.discard.push(game.pending.value);const hidden=game.people[0].board.find(card=>!card.up&&!card.removed);if(hidden)hidden.up=true;removeColumns(game.people[0]);log(`Vous défaussez ${game.pending.value} et révélez une carte.`);nextTurn()}
function botPlay(){if(game.over||game.turn===0)return;const player=game.people[game.turn];const discard=game.discard.at(-1);const visibleCards=player.board.filter(visible);const worst=visibleCards.sort((a,b)=>b.value-a.value)[0];const position=player.board.indexOf(worst||player.board.find(card=>!card.up&&!card.removed));const use=discard!==undefined&&discard<=(worst?.value??8);const card=use?game.discard.pop():drawCard();if(use||card<=(worst?.value??8)){const old=player.board[position];player.board[position]={value:card,up:true,removed:false};if(old&&!old.removed)game.discard.push(old.value);log(`${name(game.turn)} remplace une carte.`)}else{game.discard.push(card);const hidden=player.board.find(current=>!current.up&&!current.removed);if(hidden)hidden.up=true;log(`${name(game.turn)} défausse et révèle une carte.`)}removeColumns(player);nextTurn()}
function scheduleBot(){clearTimeout(botTimer);if(!game.over&&game.turn!==0)botTimer=setTimeout(botPlay,650+Math.random()*650)}
function render(){table.innerHTML=game.people.map((player,index)=>`<section class="player${index===game.turn?' active':''}"><strong>${name(index)}</strong><div class="grid">${player.board.map((card,cell)=>{const canReplace=index===0&&game.turn===0&&game.pending&&!card.removed;return `<button class="card${card.removed?' removed':''}${!card.up?' back':''}${card.value<0?' negative':''}${canReplace?' selectable':''}" data-player="${index}" data-cell="${cell}">${card.up?card.value:'?'}</button>`}).join('')}</div><small>${boardScore(player)} points visibles</small></section>`).join('');table.querySelectorAll('[data-player="0"]').forEach(cell=>cell.addEventListener('click',()=>replace(Number(cell.dataset.cell))));deckButton.disabled=game.over||game.turn!==0||Boolean(game.pending);deckButton.textContent=game.pending&&!game.pending.fromDiscard?game.pending.value:'PIOCHE';deckButton.classList.toggle('pending',Boolean(game.pending&&!game.pending.fromDiscard));discardButton.disabled=game.over||game.turn!==0||Boolean(game.pending)||!game.discard.length;discardButton.textContent=game.discard.at(-1)??'—';discardButton.classList.toggle('pending',Boolean(game.pending?.fromDiscard));discardDrawButton.hidden=!(game.pending&&!game.pending.fromDiscard&&game.turn===0);scores.innerHTML=game.people.map((player,index)=>`<p><strong>${name(index)}</strong> : ${player.score} pts</p>`).join('');document.getElementById('log').innerHTML=game.log.map(entry=>`<li>${entry}</li>`).join('')}
function startRound(){game.deck=makeDeck();game.discard=[drawCard()];game.people.forEach(player=>{player.board=Array.from({length:12},()=>({value:drawCard(),up:false,removed:false}));shuffle(player.board.map((_,i)=>i)).slice(0,2).forEach(i=>player.board[i].up=true)});game.turn=game.people.map((player,index)=>({index,total:player.board.filter(card=>card.up).reduce((sum,card)=>sum+card.value,0)})).sort((left,right)=>right.total-left.total)[0].index;game.finisher=null;game.pending=null;status.textContent=`Nouvelle manche : ${name(game.turn)} commence avec le total visible le plus élevé.`;render();scheduleBot()}
function newGame(){clearTimeout(botTimer);game={people:Array.from({length:Number(playersSelect.value)},()=>({score:0,board:[]})),round:1,turn:0,deck:[],discard:[],pending:null,finisher:null,over:false,log:[]};startRound()}
document.getElementById('newGame').addEventListener('click',newGame);playersSelect.addEventListener('change',newGame);deckButton.addEventListener('click',draw);discardButton.addEventListener('click',useDiscard);discardDrawButton.addEventListener('click',discardAndReveal);columnsOption.addEventListener('change',render);doubleFinishOption.addEventListener('change',render);localStorage.setItem('game-hub:last-game','grille-zero');newGame();
