import('../../../shared/options-help.js?v=3');
const peopleEl=document.getElementById('people'),handEl=document.getElementById('hand'),trickEl=document.getElementById('trick'),statusEl=document.getElementById('status'),bidsEl=document.getElementById('bids'),playersEl=document.getElementById('players');let game,timer,sortBySuit=true,autosave,lanPirateState=null,lanPirateSeatOrder=[],lanPirateNames=[],lanPiratePending=false;
document.querySelector('.bar').insertAdjacentHTML('beforeend','<label><input id="pirateCreatures" type="checkbox"> créatures marines</label><label class="muted">Durée <select id="pirateRounds"><option value="6">6 manches</option><option value="10" selected>10 manches</option><option value="all">complète</option></select></label>');
const pirateCreatures=document.getElementById('pirateCreatures'),pirateRounds=document.getElementById('pirateRounds');
document.title='Roi Pirate';document.querySelector('h1').textContent='Roi Pirate';
document.getElementById('rules').textContent='Faites votre enchère avant chaque manche. Les cartes spéciales restent toujours jouables. Noir est l’atout ; Corsaires, Roi Pirate et Oracles suivent leur hiérarchie. Les bonus ne comptent que si l’enchère est exacte.';
document.querySelector('h2:last-of-type').insertAdjacentHTML('beforeend',' <button id="sortHand">Trier par puissance</button>');const sortHandButton=document.getElementById('sortHand');document.head.insertAdjacentHTML('beforeend','<style>.card.blue{background:linear-gradient(145deg,#fff 0 57%,#dbeafe 58% 100%);color:#17243a}.card.red{background:linear-gradient(145deg,#fff 0 57%,#fee2e2 58% 100%);color:#17243a}.card.yellow{background:linear-gradient(145deg,#fff 0 57%,#fef3c7 58% 100%);color:#17243a}.card.black{background:linear-gradient(145deg,#fff 0 57%,#cbd5e1 58% 100%);color:#17243a}.card.special{background:linear-gradient(145deg,#fff7ed,#f97316);color:#431407}.card.special:before{content:"☠";display:block;font-size:27px}</style>');
const suits=['red','blue','yellow','black'];const labels={red:'Rouge',blue:'Bleu',yellow:'Jaune',black:'Noir'};
function shuffle(values){for(let i=values.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[values[i],values[j]]=[values[j],values[i]]}return values}
function makeDeck(){const deck=[];suits.forEach(suit=>{for(let value=1;value<=14;value++)deck.push({type:'number',suit,value})});for(let i=0;i<5;i++)deck.push({type:'escape',label:'Fuite'});for(let i=0;i<5;i++)deck.push({type:'pirate',label:'Corsaire'});for(let i=0;i<2;i++)deck.push({type:'mermaid',label:'Oracle'});deck.push({type:'king',label:'Roi Pirate'});if(pirateCreatures.checked)deck.push({type:'kraken',label:'Kraken'},{type:'whale',label:'Baleine blanche'});return shuffle(deck)}
function playerName(index){return index?'Bot '+index:'Vous'}
function cardText(card){return card.type==='number'?`${labels[card.suit]} ${card.value}`:card.label}
function cardClass(card){return card.type==='number'?card.suit:'special'}
function start(){clearTimeout(timer);const count=Number(playersEl.value),deckSize=makeDeck().length,available=Math.floor(deckSize/count),requested=pirateRounds.value==='all'?available:Number(pirateRounds.value);game={round:1,maxRounds:Math.min(requested,available),deck:[],people:Array.from({length:count},()=>({hand:[],bid:null,tricks:0,score:0})),leader:0,turn:0,trick:[],phase:'bid',done:false};dealRound();render();autosave?.save()}
function dealRound(){game.deck=makeDeck();game.leader=(game.round-1)%game.people.length;game.people.forEach(person=>{person.hand=[];person.bid=null;person.tricks=0;person.bonus=0});for(let n=0;n<game.round;n++)game.people.forEach(person=>person.hand.push(game.deck.pop()));game.turn=0;game.trick=[];game.phase='bid';statusEl.textContent=`Manche ${game.round}/${game.maxRounds} : annoncez le nombre de plis que vous pensez gagner.`}
function botBid(index){const hand=game.people[index].hand;const strong=hand.filter(card=>card.type==='king'||card.type==='pirate'||(card.type==='number'&&card.suit==='black'&&card.value>8)).length;game.people[index].bid=Math.min(game.round,Math.max(0,strong+(Math.random()<.28?0:-1)))}
function bid(value){if(game.phase!=='bid'||game.turn!==0)return;game.people[0].bid=value;for(let i=1;i<game.people.length;i++)botBid(i);game.phase='play';game.turn=game.leader;statusEl.textContent=`Manche ${game.round} : ${playerName(game.turn)} ouvre le pli.`;render();queueBot()}
function legalCards(person){const leading=game.trick.find(entry=>entry.card.type==='number');if(!leading)return person.hand;const matching=person.hand.filter(card=>card.type==='number'&&card.suit===leading.card.suit);return matching.length?[...matching,...person.hand.filter(card=>card.type!=='number')]:person.hand}
function rank(entry){const card=entry.card;if(card.type==='mermaid')return game.trick.some(item=>item.card.type==='king')?1000:700;if(card.type==='king')return 900;if(card.type==='pirate')return 800;if(card.type==='escape'||card.type==='kraken'||card.type==='whale')return 0;if(card.suit==='black')return 600+card.value;const lead=game.trick.find(item=>item.card.type==='number')?.card.suit;return card.suit===lead?100+card.value:card.value}
function winner(){const creatures=game.trick.filter(entry=>entry.card.type==='kraken'||entry.card.type==='whale'),activeCreature=creatures.at(-1),ordinary=game.trick.filter(entry=>entry.card.type!=='kraken'&&entry.card.type!=='whale'),normalWinner=ordinary.reduce((best,item)=>!best||rank(item)>rank(best)?item:best,null);if(activeCreature?.card.type==='kraken')return{player:null,nextLeader:normalWinner?.player??activeCreature.player,label:'Le Kraken engloutit le pli'};if(activeCreature?.card.type==='whale'){const numbers=ordinary.filter(entry=>entry.card.type==='number');const winning=numbers.reduce((best,item)=>!best||item.card.value>best.card.value?item:best,null);return winning?{player:winning.player,nextLeader:winning.player,label:'La Baleine blanche neutralise couleurs et personnages'}:{player:activeCreature.player,nextLeader:activeCreature.player,label:'La Baleine blanche reste seule en jeu'}}return{player:normalWinner.player,nextLeader:normalWinner.player,label:''}}
function play(index){if(game.phase!=='play'||game.turn!==0||game.done)return;const person=game.people[0],card=person.hand[index];if(!legalCards(person).includes(card)){statusEl.textContent='Vous devez suivre la couleur si vous le pouvez.';return}place(card,0,index)}
function trickBonus(winnerIndex){const winning=game.trick.find(entry=>entry.player===winnerIndex&&rank(entry)===Math.max(...game.trick.map(rank)))?.card;let bonus=game.trick.filter(entry=>entry.card.type==='number'&&entry.card.value===14).reduce((sum,entry)=>sum+(entry.card.suit==='black'?20:10),0);if(winning?.type==='pirate')bonus+=20*game.trick.filter(entry=>entry.card.type==='mermaid').length;if(winning?.type==='king')bonus+=30*game.trick.filter(entry=>entry.card.type==='pirate').length;if(winning?.type==='mermaid'&&game.trick.some(entry=>entry.card.type==='king'))bonus+=40;return bonus}
function place(card,who,index){game.people[who].hand.splice(index,1);game.trick.push({card,player:who});window.GameEffects?.play('move');game.turn=(who+1)%game.people.length;if(game.trick.length===game.people.length){const outcome=winner(),won=outcome.player,bonus=won===null?0:trickBonus(won);if(won!==null){game.people[won].tricks++;game.people[won].bonus+=bonus}game.leader=outcome.nextLeader;game.turn=outcome.nextLeader;statusEl.textContent=won===null?`${outcome.label}. ${playerName(outcome.nextLeader)} ouvre le prochain pli.`:`${outcome.label?`${outcome.label}. `:''}${playerName(won)} remporte le pli${bonus?` et réserve ${bonus} points bonus`:''}.`;render();timer=setTimeout(()=>{game.trick=[];if(game.people.every(person=>!person.hand.length))finishRound();else{render();queueBot()}},850)}else{render();queueBot()}}
function botPlay(){if(game.phase!=='play'||game.turn===0||game.done)return;const person=game.people[game.turn],cards=legalCards(person);const card=cards[Math.floor(Math.random()*cards.length)];place(card,game.turn,person.hand.indexOf(card))}
function queueBot(){clearTimeout(timer);if(game.phase==='play'&&game.turn!==0&&!game.done)timer=setTimeout(botPlay,550+Math.random()*550)}
function finishRound(){game.people.forEach(person=>{const correct=person.tricks===person.bid;const delta=correct?(person.bid===0?10*game.round:20*person.bid)+person.bonus:person.bid===0?-10*game.round:-10*Math.abs(person.tricks-person.bid);person.score+=delta});if(game.round===game.maxRounds){game.done=true;const high=Math.max(...game.people.map(person=>person.score));const winner=game.people.findIndex(person=>person.score===high);statusEl.textContent=`Partie terminée : ${playerName(winner)} gagne avec ${high} points.`;window.GameRecords?.finish({score:high,scoreLabel:`${high} points`,won:winner===0});render();return}game.round++;dealRound();render()}
function render(){const me=game.people[0];peopleEl.innerHTML=game.people.map((person,index)=>`<article class="player${game.phase==='play'&&index===game.turn?' active':''}"><strong>${playerName(index)}</strong><br><small>Score ${person.score} · Enchère ${person.bid??'—'} · Plis ${person.tricks}</small><br><small>${person.hand.length} carte${person.hand.length>1?'s':''} · bonus en réserve ${person.bonus||0}</small></article>`).join('');bidsEl.innerHTML=game.phase==='bid'?`<strong>Votre enchère :</strong>${Array.from({length:game.round+1},(_,n)=>`<button data-bid="${n}">${n}</button>`).join('')}`:'';bidsEl.querySelectorAll('[data-bid]').forEach(button=>button.onclick=()=>bid(Number(button.dataset.bid)));trickEl.innerHTML=game.trick.length?game.trick.map(entry=>`<article class="card ${cardClass(entry.card)}"><small>${playerName(entry.player)}</small><br>${cardText(entry.card)}</article>`).join(''):'<span class="muted">Le pli attend sa première carte.</span>';const cards=me.hand.map((card,index)=>({card,index})).sort((a,b)=>sortBySuit?(cardClass(a.card).localeCompare(cardClass(b.card))||((a.card.value||99)-(b.card.value||99))):((a.card.value||99)-(b.card.value||99)));handEl.innerHTML=cards.map(({card,index})=>`<button class="card ${cardClass(card)}" data-card="${index}">${cardText(card)}</button>`).join('');handEl.querySelectorAll('[data-card]').forEach(button=>button.onclick=()=>play(Number(button.dataset.card)));sortHandButton.textContent=sortBySuit?'Trier par puissance':'Trier par couleur'}
window.RoiPirateTestAPI=Object.freeze({diagnostics:()=>{const cards=makeDeck();return{deckSize:cards.length,numbers:cards.filter(card=>card.type==='number').length,escapes:cards.filter(card=>card.type==='escape').length,pirates:cards.filter(card=>card.type==='pirate').length,mermaids:cards.filter(card=>card.type==='mermaid').length,kings:cards.filter(card=>card.type==='king').length,creatures:cards.filter(card=>card.type==='kraken'||card.type==='whale').length};}});document.getElementById('newGame').onclick=start;playersEl.onchange=start;pirateCreatures.onchange=start;pirateRounds.onchange=start;sortHandButton.onclick=()=>{sortBySuit=!sortBySuit;render()};if(!window.GameEffects){const script=document.createElement('script');script.src='../../../shared/effects.js?v=1';document.head.appendChild(script)}localStorage.setItem('game-hub:last-game','roi-pirate');autosave=window.GameRuntime?.createAutosave('partie',{capture:()=>game,validate:value=>Array.isArray(value?.people)&&Array.isArray(value?.trick),restore:value=>{game=value;render();if(game.done)return;if(game.trick.length===game.people.length)timer=setTimeout(()=>{game.trick=[];if(game.people.every(person=>!person.hand.length))finishRound();else{render();queueBot()}},250);else queueBot()}});if(!autosave?.restore())start();

const localPirateBid=bid,localPiratePlay=play,localPiratePlayerName=playerName;
function pirateLocalSeat(serverSeat){return lanPirateSeatOrder.indexOf(serverSeat)}
function sendPirateAction(action){if(!window.LanMultiplayer?.active||lanPiratePending)return;lanPiratePending=true;window.LanMultiplayer.sendPrivateAction(action).catch(error=>{statusEl.textContent=`Coup refusé : ${error.message}`}).finally(()=>{lanPiratePending=false})}
function applyLanPirateState(room){const snapshot=room?.gameState;if(!snapshot||snapshot.yourSeat===null||snapshot.yourSeat===undefined){if(room?.phase==='lobby')lanPirateState=null;return}lanPirateState=snapshot;lanPiratePending=false;lanPirateSeatOrder=[snapshot.yourSeat,...snapshot.handCounts.map((_,index)=>index).filter(index=>index!==snapshot.yourSeat)];lanPirateNames=lanPirateSeatOrder.map((seat,index)=>room.seats?.[seat]?.label||(index?'Adversaire':'Vous'));game={round:snapshot.round,maxRounds:snapshot.maxRounds,deck:[],people:lanPirateSeatOrder.map((seat,index)=>({hand:index===0?snapshot.hand.map(card=>({...card})):Array.from({length:snapshot.handCounts[seat]},()=>({type:'hidden',label:'Carte cachée'})),bid:snapshot.bids[seat],tricks:snapshot.tricks[seat],score:snapshot.scores[seat],bonus:snapshot.bonus[seat]})),leader:pirateLocalSeat(snapshot.leader),turn:pirateLocalSeat(snapshot.current),trick:snapshot.trick.map(entry=>({player:pirateLocalSeat(entry.seat),card:{...entry.card}})),phase:snapshot.phase,done:snapshot.done};const myBidSent=snapshot.bidSubmitted[snapshot.yourSeat];if(snapshot.done){const winnerName=room.seats?.[snapshot.winner]?.label||'Un joueur';statusEl.textContent=snapshot.winner===snapshot.yourSeat?`Vous gagnez la partie LAN avec ${snapshot.scores[snapshot.yourSeat]} points.`:`${winnerName} gagne avec ${snapshot.scores[snapshot.winner]} points.`}else if(snapshot.phase==='bid')statusEl.textContent=myBidSent?'Enchère secrète enregistrée, attente des autres joueurs.':`Manche ${snapshot.round}/${snapshot.maxRounds} : choisissez votre enchère secrète.`;else if(snapshot.current===snapshot.yourSeat)statusEl.textContent='À vous de jouer une carte.';else statusEl.textContent=snapshot.message||`Au tour de ${room.seats?.[snapshot.current]?.label||'un adversaire'}.`;render();if(snapshot.phase==='bid'&&myBidSent)bidsEl.innerHTML='<span class="muted">Votre enchère est enregistrée.</span>';handEl.querySelectorAll('[data-card]').forEach(button=>{button.disabled=snapshot.phase!=='play'||snapshot.current!==snapshot.yourSeat||lanPiratePending})}
playerName=function lanAwarePirateName(index){return lanPirateState?(lanPirateNames[index]||`Joueur ${index+1}`):localPiratePlayerName(index)};
bid=function lanAwarePirateBid(value){if(!lanPirateState)return localPirateBid(value);if(lanPirateState.phase!=='bid'||lanPirateState.bidSubmitted[lanPirateState.yourSeat]||lanPiratePending)return;sendPirateAction({type:'bid',value})};
play=function lanAwarePiratePlay(index){if(!lanPirateState)return localPiratePlay(index);if(lanPirateState.phase!=='play'||lanPirateState.current!==lanPirateState.yourSeat||lanPiratePending)return;const card=game.people[0].hand[index];if(card)sendPirateAction({type:'play',cardId:card.id})};
window.addEventListener('lan:room',event=>applyLanPirateState(event.detail?.room));
window.addEventListener('lan:left',()=>{lanPirateState=null;lanPirateSeatOrder=[];lanPirateNames=[];start()});
