const peopleEl=document.getElementById('people'),handEl=document.getElementById('hand'),trickEl=document.getElementById('trick'),statusEl=document.getElementById('status'),bidsEl=document.getElementById('bids'),playersEl=document.getElementById('players');let game,timer,sortBySuit=true;
document.title='Roi Pirate';document.querySelector('h1').textContent='Roi Pirate';
document.getElementById('rules').textContent='Faites votre enchère avant chaque manche. Les cartes spéciales restent toujours jouables. Noir est l’atout ; Corsaires, Roi Pirate et Oracles suivent leur hiérarchie. Les bonus ne comptent que si l’enchère est exacte.';
document.querySelector('h2:last-of-type').insertAdjacentHTML('beforeend',' <button id="sortHand">Trier par puissance</button>');const sortHandButton=document.getElementById('sortHand');document.head.insertAdjacentHTML('beforeend','<style>.card.blue{background:linear-gradient(145deg,#fff 0 57%,#dbeafe 58% 100%);color:#17243a}.card.red{background:linear-gradient(145deg,#fff 0 57%,#fee2e2 58% 100%);color:#17243a}.card.yellow{background:linear-gradient(145deg,#fff 0 57%,#fef3c7 58% 100%);color:#17243a}.card.black{background:linear-gradient(145deg,#fff 0 57%,#cbd5e1 58% 100%);color:#17243a}.card.special{background:linear-gradient(145deg,#fff7ed,#f97316);color:#431407}.card.special:before{content:"☠";display:block;font-size:27px}</style>');
const suits=['red','blue','yellow','black'];const labels={red:'Rouge',blue:'Bleu',yellow:'Jaune',black:'Noir'};
function shuffle(values){for(let i=values.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[values[i],values[j]]=[values[j],values[i]]}return values}
function makeDeck(){const deck=[];suits.forEach(suit=>{for(let value=1;value<=14;value++)deck.push({type:'number',suit,value})});for(let i=0;i<5;i++)deck.push({type:'escape',label:'Fuite'});for(let i=0;i<5;i++)deck.push({type:'pirate',label:'Corsaire'});for(let i=0;i<2;i++)deck.push({type:'mermaid',label:'Oracle'});deck.push({type:'king',label:'Roi Pirate'});return shuffle(deck)}
function playerName(index){return index?'Bot '+index:'Vous'}
function cardText(card){return card.type==='number'?`${labels[card.suit]} ${card.value}`:card.label}
function cardClass(card){return card.type==='number'?card.suit:'special'}
function start(){clearTimeout(timer);const count=Number(playersEl.value),deckSize=makeDeck().length;game={round:1,maxRounds:Math.min(10,Math.floor(deckSize/count)),deck:[],people:Array.from({length:count},()=>({hand:[],bid:null,tricks:0,score:0})),leader:0,turn:0,trick:[],phase:'bid',done:false};dealRound();render()}
function dealRound(){game.deck=makeDeck();game.leader=(game.round-1)%game.people.length;game.people.forEach(person=>{person.hand=[];person.bid=null;person.tricks=0;person.bonus=0});for(let n=0;n<game.round;n++)game.people.forEach(person=>person.hand.push(game.deck.pop()));game.turn=0;game.trick=[];game.phase='bid';statusEl.textContent=`Manche ${game.round}/${game.maxRounds} : annoncez le nombre de plis que vous pensez gagner.`}
function botBid(index){const hand=game.people[index].hand;const strong=hand.filter(card=>card.type==='king'||card.type==='pirate'||(card.type==='number'&&card.suit==='black'&&card.value>8)).length;game.people[index].bid=Math.min(game.round,Math.max(0,strong+(Math.random()<.28?0:-1)))}
function bid(value){if(game.phase!=='bid'||game.turn!==0)return;game.people[0].bid=value;for(let i=1;i<game.people.length;i++)botBid(i);game.phase='play';game.turn=game.leader;statusEl.textContent=`Manche ${game.round} : ${playerName(game.turn)} ouvre le pli.`;render();queueBot()}
function legalCards(person){const leading=game.trick.find(entry=>entry.card.type==='number');if(!leading)return person.hand;const matching=person.hand.filter(card=>card.type==='number'&&card.suit===leading.card.suit);return matching.length?[...matching,...person.hand.filter(card=>card.type!=='number')]:person.hand}
function rank(entry){const card=entry.card;if(card.type==='mermaid')return game.trick.some(item=>item.card.type==='king')?1000:700;if(card.type==='king')return 900;if(card.type==='pirate')return 800;if(card.type==='escape')return 0;if(card.suit==='black')return 600+card.value;const lead=game.trick.find(item=>item.card.type==='number')?.card.suit;return card.suit===lead?100+card.value:card.value}
function winner(){return game.trick.reduce((best,item)=>rank(item)>rank(best)?item:best).player}
function play(index){if(game.phase!=='play'||game.turn!==0||game.done)return;const person=game.people[0],card=person.hand[index];if(!legalCards(person).includes(card)){statusEl.textContent='Vous devez suivre la couleur si vous le pouvez.';return}place(card,0,index)}
function trickBonus(winnerIndex){const winning=game.trick.find(entry=>entry.player===winnerIndex&&rank(entry)===Math.max(...game.trick.map(rank)))?.card;let bonus=game.trick.filter(entry=>entry.card.type==='number'&&entry.card.value===14).reduce((sum,entry)=>sum+(entry.card.suit==='black'?20:10),0);if(winning?.type==='pirate')bonus+=20*game.trick.filter(entry=>entry.card.type==='mermaid').length;if(winning?.type==='king')bonus+=30*game.trick.filter(entry=>entry.card.type==='pirate').length;if(winning?.type==='mermaid'&&game.trick.some(entry=>entry.card.type==='king'))bonus+=40;return bonus}
function place(card,who,index){game.people[who].hand.splice(index,1);game.trick.push({card,player:who});window.GameEffects?.play('move');game.turn=(who+1)%game.people.length;if(game.trick.length===game.people.length){const won=winner(),bonus=trickBonus(won);game.people[won].tricks++;game.people[won].bonus+=bonus;game.leader=won;game.turn=won;statusEl.textContent=`${playerName(won)} remporte le pli${bonus?` et réserve ${bonus} points bonus`:''}.`;render();timer=setTimeout(()=>{game.trick=[];if(game.people.every(person=>!person.hand.length))finishRound();else{render();queueBot()}},850)}else{render();queueBot()}}
function botPlay(){if(game.phase!=='play'||game.turn===0||game.done)return;const person=game.people[game.turn],cards=legalCards(person);const card=cards[Math.floor(Math.random()*cards.length)];place(card,game.turn,person.hand.indexOf(card))}
function queueBot(){clearTimeout(timer);if(game.phase==='play'&&game.turn!==0&&!game.done)timer=setTimeout(botPlay,550+Math.random()*550)}
function finishRound(){game.people.forEach(person=>{const correct=person.tricks===person.bid;const delta=correct?(person.bid===0?10*game.round:20*person.bid)+person.bonus:person.bid===0?-10*game.round:-10*Math.abs(person.tricks-person.bid);person.score+=delta});if(game.round===game.maxRounds){game.done=true;const high=Math.max(...game.people.map(person=>person.score));statusEl.textContent=`Partie terminée : ${playerName(game.people.findIndex(person=>person.score===high))} gagne avec ${high} points.`;render();return}game.round++;dealRound();render()}
function render(){const me=game.people[0];peopleEl.innerHTML=game.people.map((person,index)=>`<article class="player${game.phase==='play'&&index===game.turn?' active':''}"><strong>${playerName(index)}</strong><br><small>Score ${person.score} · Enchère ${person.bid??'—'} · Plis ${person.tricks}</small><br><small>${person.hand.length} carte${person.hand.length>1?'s':''} · bonus en réserve ${person.bonus||0}</small></article>`).join('');bidsEl.innerHTML=game.phase==='bid'?`<strong>Votre enchère :</strong>${Array.from({length:game.round+1},(_,n)=>`<button data-bid="${n}">${n}</button>`).join('')}`:'';bidsEl.querySelectorAll('[data-bid]').forEach(button=>button.onclick=()=>bid(Number(button.dataset.bid)));trickEl.innerHTML=game.trick.length?game.trick.map(entry=>`<article class="card ${cardClass(entry.card)}"><small>${playerName(entry.player)}</small><br>${cardText(entry.card)}</article>`).join(''):'<span class="muted">Le pli attend sa première carte.</span>';const cards=me.hand.map((card,index)=>({card,index})).sort((a,b)=>sortBySuit?(cardClass(a.card).localeCompare(cardClass(b.card))||((a.card.value||99)-(b.card.value||99))):((a.card.value||99)-(b.card.value||99)));handEl.innerHTML=cards.map(({card,index})=>`<button class="card ${cardClass(card)}" data-card="${index}">${cardText(card)}</button>`).join('');handEl.querySelectorAll('[data-card]').forEach(button=>button.onclick=()=>play(Number(button.dataset.card)));sortHandButton.textContent=sortBySuit?'Trier par puissance':'Trier par couleur'}
document.getElementById('newGame').onclick=start;playersEl.onchange=start;sortHandButton.onclick=()=>{sortBySuit=!sortBySuit;render()};if(!window.GameEffects){const script=document.createElement('script');script.src='../../../shared/effects.js?v=1';document.head.appendChild(script)}localStorage.setItem('game-hub:last-game','roi-pirate');start();
