const rowsElement=document.getElementById('rows'),handElement=document.getElementById('hand'),statusElement=document.getElementById('status'),scoresElement=document.getElementById('scores'),playersSelect=document.getElementById('players'),limitSelect=document.getElementById('limit');let game,sortByHorns=false;
document.title='Sixième Carte';document.querySelector('h1').textContent='Sixième Carte';
document.querySelector('h2').insertAdjacentHTML('beforeend',' <button id="sortHand">Trier par têtes</button>');const sortHandButton=document.getElementById('sortHand');document.head.insertAdjacentHTML('beforeend','<style>.card{background:#fff;box-shadow:inset 0 0 0 3px #fff,0 2px 3px #0002}.card:before{content:"🐂";position:absolute;left:4px;top:2px;font-size:11px;opacity:.65}.card.horns-2{border-color:#d6a10c;background:#fef3c7}.card.horns-3{border-color:#2563eb;background:#dbeafe}.card.horns-5,.card.horns-7{border-color:#b91c1c;background:#fee2e2}.card.horns-7{box-shadow:inset 0 0 0 3px #fff,0 0 0 3px #7f1d1d}</style>');
document.head.insertAdjacentHTML('beforeend','<style>.row .card{display:inline-grid;place-items:center;box-sizing:border-box}.row.selectable-row{cursor:pointer;outline:4px solid #7c3aed;outline-offset:2px}.row.selectable-row:hover,.row.selectable-row:focus{background:#ede9fe;transform:translateX(5px)}</style>');
function horns(number){if(number===55)return 7;if(number%11===0)return 5;if(number%10===0)return 3;if(number%10===5)return 2;return 1}function shuffle(values){for(let i=values.length-1;i>0;i-=1){const j=Math.floor(Math.random()*(i+1));[values[i],values[j]]=[values[j],values[i]]}return values}function name(i){return i===0?'Vous':`Bot ${i}`}function log(text){game.log.unshift(text);game.log=game.log.slice(0,8)}function score(row){return row.reduce((sum,card)=>sum+horns(card),0)}
function place(player,card){const ends=game.rows.map(row=>row.at(-1));const choices=ends.map((end,index)=>({end,index})).filter(choice=>choice.end<card).sort((a,b)=>b.end-a.end);if(!choices.length){const target=game.rows.map((row,index)=>({index,score:score(row)})).sort((a,b)=>a.score-b.score)[0];game.people[player].points+=target.score;game.rows[target.index]=[card];log(`${name(player)} prend ${target.score} têtes.`);return}const target=choices[0].index;if(game.rows[target].length===5){const penalty=score(game.rows[target]);game.people[player].points+=penalty;game.rows[target]=[card];log(`${name(player)} prend ${penalty} têtes avec le 6e bœuf.`)}else game.rows[target].push(card)}
function finishTurn(){game.round+=1;if(game.people.some(player=>player.points>=Number(limitSelect.value))){const winner=game.people.map((player,index)=>({index,points:player.points})).sort((a,b)=>a.points-b.points)[0];statusElement.textContent=`${name(winner.index)} gagne avec ${winner.points} têtes.`;game.over=true;render();return}if(game.people[0].hand.length===0){log(`Fin de manche : ${game.people.map((player,index)=>`${name(index)} ${player.points}`).join(' · ')}.`);startRound();return}statusElement.textContent='Choisissez une carte.';render()}
function continueResolution(){while(game.queue.length){const choice=game.queue.shift();const canFollow=game.rows.some(row=>row.at(-1)<choice.card);if(choice.player===0&&!canFollow){game.pendingRow=choice;statusElement.textContent=`Votre ${choice.card} est plus petit que toutes les fins de rangée : choisissez celle que vous prenez.`;render();return}place(choice.player,choice.card)}finishTurn()}
function resolve(selected){game.queue=selected.sort((a,b)=>a.card-b.card);continueResolution()}
function chooseRow(index){if(!game.pendingRow||game.over)return;const choice=game.pendingRow,penalty=score(game.rows[index]);game.people[choice.player].points+=penalty;game.rows[index]=[choice.card];game.pendingRow=null;log(`Vous choisissez la rangée ${index+1} et prenez ${penalty} têtes.`);continueResolution()}
function choose(card){if(game.over)return;const selected=[{player:0,card:game.people[0].hand.splice(game.people[0].hand.indexOf(card),1)[0]}];game.people.slice(1).forEach((player,index)=>{const sorted=player.hand.slice().sort((a,b)=>a-b);const safe=sorted.filter(value=>game.rows.some(row=>row.at(-1)<value));const chosen=(safe[0]??sorted[0]);player.hand.splice(player.hand.indexOf(chosen),1);selected.push({player:index+1,card:chosen})});resolve(selected)}
function cardMarkup(card){return `<span class="card horns-${horns(card)}">${card}<small>🐂${horns(card)}</small></span>`}function render(){rowsElement.innerHTML=game.rows.map((row,index)=>`<div class="row${game.pendingRow?' selectable-row':''}" data-row="${index}" role="${game.pendingRow?'button':'group'}" tabindex="${game.pendingRow?'0':'-1'}"><span class="muted">${index+1}</span>${row.map(card=>cardMarkup(card)).join('')}</div>`).join('');rowsElement.querySelectorAll('[data-row]').forEach(row=>{row.onclick=()=>chooseRow(Number(row.dataset.row));row.onkeydown=event=>{if(game.pendingRow&&(event.key==='Enter'||event.key===' '))chooseRow(Number(row.dataset.row))}});const cards=game.people[0].hand.slice().sort((a,b)=>sortByHorns?horns(a)-horns(b)||a-b:a-b);handElement.innerHTML=cards.map(card=>`<button class="card horns-${horns(card)}" data-card="${card}"${game.pendingRow||game.queue?.length?' disabled':''}>${card}<small>🐂${horns(card)}</small></button>`).join('');handElement.querySelectorAll('[data-card]').forEach(button=>button.addEventListener('click',()=>choose(Number(button.dataset.card))));sortHandButton.textContent=sortByHorns?'Trier par valeur':'Trier par têtes';scoresElement.innerHTML=game.people.map((player,index)=>`<div class="score"><strong>${name(index)}</strong> : ${player.points} têtes</div>`).join('');document.getElementById('log').innerHTML=game.log.map(entry=>`<li>${entry}</li>`).join('')}
function startRound(){const cards=shuffle(Array.from({length:104},(_,index)=>index+1));game.rows=cards.splice(0,4).map(card=>[card]);game.people.forEach(player=>{player.hand=[]});for(let turn=0;turn<10;turn+=1)game.people.forEach(player=>player.hand.push(cards.pop()));game.round=0;game.queue=[];game.pendingRow=null;statusElement.textContent='Nouvelle manche : choisissez une carte, elles seront résolues dans l’ordre croissant.';render()}
function newGame(){const players=Number(playersSelect.value);game={people:Array.from({length:players},()=>({points:0,hand:[]})),rows:[],round:0,queue:[],pendingRow:null,log:[],over:false};startRound()}document.getElementById('newGame').addEventListener('click',newGame);playersSelect.addEventListener('change',newGame);limitSelect.addEventListener('change',newGame);sortHandButton.addEventListener('click',()=>{sortByHorns=!sortByHorns;render()});localStorage.setItem('game-hub:last-game','sixieme-carte');newGame();
