const fileInput=document.getElementById('file'),statusElement=document.getElementById('status'),summaryElement=document.getElementById('summary'),timelineElement=document.getElementById('timeline'),previousButton=document.getElementById('previous'),nextButton=document.getElementById('next'),playButton=document.getElementById('play'),speedSelect=document.getElementById('speed'),filterSelect=document.getElementById('filter');
let replay=null,visibleEvents=[],current=-1,playTimer=0;
const clean=value=>String(value??'').replace(/[<>]/g,'');
function describe(event){const payload=event.payload||{};if(event.type==='action')return `${payload.action?.type||'action'} · ${JSON.stringify(payload.action||{})}`;if(event.type==='start')return 'Départ commun';if(event.type==='pause')return payload.paused?'Pause':'Reprise';if(event.type==='finished')return 'Partie terminée';if(event.type==='game-state')return `État privé n°${payload.version||'?'}`;return JSON.stringify(payload);}
function stop(){clearTimeout(playTimer);playTimer=0;playButton.textContent='Lecture'}
function render(){visibleEvents=(replay?.events||[]).filter(event=>!filterSelect.value||event.type===filterSelect.value);current=Math.min(current,visibleEvents.length-1);timelineElement.innerHTML=visibleEvents.length?visibleEvents.map((event,index)=>`<li class="event${index===current?' current':''}" data-event="${index}"><time>#${event.sequence??index+1}</time><strong>${clean(event.type)}</strong><code>${clean(describe(event))}</code></li>`).join(''):'<li class="empty">Aucun événement pour ce filtre.</li>';timelineElement.querySelector('.current')?.scrollIntoView({block:'nearest',behavior:'smooth'});previousButton.disabled=current<=0;nextButton.disabled=current>=visibleEvents.length-1;playButton.disabled=!visibleEvents.length}
function select(index){current=Math.max(0,Math.min(visibleEvents.length-1,index));render()}
function tick(){if(current>=visibleEvents.length-1){stop();return}const previous=visibleEvents[Math.max(0,current)],next=visibleEvents[current+1];select(current+1);const natural=Math.max(180,Math.min(2200,((next?.at||0)-(previous?.at||0))*1000));playTimer=setTimeout(tick,natural*Number(speedSelect.value))}
function load(payload){if(payload?.format!=='ludotheque-lan-replay'||![1,2].includes(payload.version)||!Array.isArray(payload.events))throw new Error('Ce fichier n’est pas un replay LAN compatible.');replay=payload;current=payload.events.length?0:-1;const types=[...new Set(payload.events.map(event=>event.type).filter(Boolean))].sort();filterSelect.innerHTML='<option value="">Tous</option>'+types.map(type=>`<option>${clean(type)}</option>`).join('');const duration=Number(payload.duration)||Math.max(0,(payload.events.at(-1)?.at||0)-(payload.events[0]?.at||0));summaryElement.hidden=false;summaryElement.innerHTML=`<div><strong>Jeu</strong><br>${clean(payload.game?.split('/').pop()?.replace('.html','')||'—')}</div><div><strong>Événements</strong><br>${payload.events.length}</div><div><strong>Durée</strong><br>${duration.toFixed(1)} s</div><div><strong>Résultat</strong><br>${clean(payload.results?.[0]?.name||'—')}</div>`;statusElement.textContent=`Replay exporté le ${new Date(payload.exportedAt||Date.now()).toLocaleString()}. Utilisez ←/→ pour avancer.`;render()}
fileInput.addEventListener('change',async()=>{stop();try{load(JSON.parse(await fileInput.files[0].text()))}catch(error){statusElement.textContent=`Import impossible : ${error.message}`}finally{fileInput.value=''}});previousButton.onclick=()=>{stop();select(current-1)};nextButton.onclick=()=>{stop();select(current+1)};playButton.onclick=()=>{if(playTimer)stop();else{playButton.textContent='Pause';tick()}};filterSelect.onchange=()=>{stop();current=0;render()};document.addEventListener('keydown',event=>{if(event.target.matches('input,select'))return;if(event.key==='ArrowLeft'){event.preventDefault();previousButton.click()}if(event.key==='ArrowRight'){event.preventDefault();nextButton.click()}if(event.key===' '){event.preventDefault();playButton.click()}});
