const boardElement = document.getElementById('board');
const titleElement = document.getElementById('title');
const statusElement = document.getElementById('status');
const rulesElement = document.getElementById('rules');
const scoreElement = document.getElementById('score');
const historyElement = document.getElementById('history');
const typeSelect = document.getElementById('gameType');
const difficultySelect = document.getElementById('difficulty');
const glyphs = { wk: '♔', wq: '♕', wr: '♖', wb: '♗', wn: '♘', wp: '♙', bk: '♚', bq: '♛', br: '♜', bb: '♝', bn: '♞', bp: '♟' };
const values = { p: 1, n: 3, b: 3, r: 5, q: 9, k: 50 };
document.querySelector('.toolbar').insertAdjacentHTML('beforeend', '<label class="muted"><input id="chainCaptures" type="checkbox" checked> Enchaîner les prises</label>');
const chainCaptures = document.getElementById('chainCaptures');
document.head.insertAdjacentHTML('beforeend', '<style>main{max-width:1180px!important}.layout{grid-template-columns:680px minmax(260px,1fr)!important;align-items:start}.board{grid-template-columns:repeat(8,82px)!important;grid-template-rows:repeat(8,82px)!important;width:656px!important;height:656px!important;aspect-ratio:auto!important;overflow:visible}.cell{width:82px!important;height:82px!important;min-width:82px!important;min-height:82px!important;overflow:visible!important}.piece{font-size:58px!important;line-height:1}.checker{min-width:56px;min-height:56px}.board{margin:0 auto}@media(max-width:980px){.layout{grid-template-columns:1fr!important}.side{margin-top:18px}}@media(max-width:700px){.board{margin-left:0}}</style>');
let game;
let botTimer;
function inBoard(row, column) { return row >= 0 && row < 8 && column >= 0 && column < 8; }
function at(row, column) { return game.board[row]?.[column] || null; }
function cloneBoard(board) { return board.map(row => row.map(piece => piece ? { ...piece } : null)); }
function other(color) { return color === 'w' ? 'b' : 'w'; }
function label(row, column) { return `${String.fromCharCode(97 + column)}${8 - row}`; }
function initialChess() { const back = ['r','n','b','q','k','b','n','r']; return Array.from({ length: 8 }, (_, row) => Array.from({ length: 8 }, (_, column) => row === 0 || row === 1 ? { c: 'b', t: row === 1 ? 'p' : back[column] } : row === 6 || row === 7 ? { c: 'w', t: row === 6 ? 'p' : back[column] } : null)); }
function initialCheckers() { return Array.from({ length: 8 }, (_, row) => Array.from({ length: 8 }, (_, column) => (row < 3 || row > 4) && (row + column) % 2 ? { c: row < 3 ? 'b' : 'w', k: false } : null)); }
function chessPseudo(board, row, column, attacks = false) { const piece = board[row][column]; if (!piece) return []; const moves = []; const add = (nextRow, nextColumn) => { if (!inBoard(nextRow, nextColumn)) return false; const target = board[nextRow][nextColumn]; if (!target || target.c !== piece.c) moves.push({ from: [row, column], to: [nextRow, nextColumn], capture: Boolean(target) }); return !target; }; if (piece.t === 'p') { const direction = piece.c === 'w' ? -1 : 1; if (attacks) [-1, 1].forEach(offset => add(row + direction, column + offset)); else { if (!atBoard(board, row + direction, column)) moves.push({ from: [row, column], to: [row + direction, column], capture: false }); if (row === (piece.c === 'w' ? 6 : 1) && !atBoard(board, row + direction, column) && !atBoard(board, row + direction * 2, column)) moves.push({ from: [row, column], to: [row + direction * 2, column], capture: false }); [-1, 1].forEach(offset => { const target = board[row + direction]?.[column + offset]; if (target && target.c !== piece.c) moves.push({ from: [row, column], to: [row + direction, column + offset], capture: true }); }); } return moves; } if (piece.t === 'n') { [[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]].forEach(([dr, dc]) => add(row + dr, column + dc)); return moves; } if (piece.t === 'k') { [-1,0,1].forEach(dr => [-1,0,1].forEach(dc => { if (dr || dc) add(row + dr, column + dc); })); return moves; } const directions = piece.t === 'b' ? [[-1,-1],[-1,1],[1,-1],[1,1]] : piece.t === 'r' ? [[-1,0],[1,0],[0,-1],[0,1]] : [[-1,-1],[-1,1],[1,-1],[1,1],[-1,0],[1,0],[0,-1],[0,1]]; directions.forEach(([dr, dc]) => { for (let step = 1; step < 8 && add(row + dr * step, column + dc * step); step += 1) {} }); return moves; }
function atBoard(board, row, column) { return inBoard(row, column) ? board[row][column] : { blocked: true }; }
function chessAttacked(board, row, column, byColor) { return board.some((line, currentRow) => line.some((piece, currentColumn) => piece?.c === byColor && chessPseudo(board, currentRow, currentColumn, piece.t === 'p').some(move => move.to[0] === row && move.to[1] === column))); }
function chessMovesFor(row, column) { const piece = at(row, column); if (!piece || piece.c !== game.turn) return []; return chessPseudo(game.board, row, column).filter(move => { const board = cloneBoard(game.board); const moved = board[row][column]; board[move.to[0]][move.to[1]] = moved; board[row][column] = null; const king = board.flatMap((line, kingRow) => line.map((item, kingColumn) => item?.c === piece.c && item.t === 'k' ? [kingRow, kingColumn] : null)).find(Boolean); return king && !chessAttacked(board, king[0], king[1], other(piece.c)); }); }
function checkerMovesFor(row, column, capturesOnly = false) { const piece = at(row, column); if (!piece || piece.c !== game.turn) return []; const directions = [[-1,-1],[-1,1],[1,-1],[1,1]]; const forward = piece.c === 'w' ? -1 : 1; const captures = []; const simple = []; directions.forEach(([dr, dc]) => { if (piece.k) { let step = 1; while (inBoard(row + dr * step, column + dc * step) && !at(row + dr * step, column + dc * step)) { simple.push({ from: [row, column], to: [row + dr * step, column + dc * step], capture: null }); step += 1; } const enemy = at(row + dr * step, column + dc * step); if (enemy && enemy.c !== piece.c) { while (inBoard(row + dr * (step + 1), column + dc * (step + 1)) && !at(row + dr * (step + 1), column + dc * (step + 1))) { captures.push({ from: [row, column], to: [row + dr * (step + 1), column + dc * (step + 1)], capture: [row + dr * step, column + dc * step] }); step += 1; } } return; } const middle = at(row + dr, column + dc); const targetRow = row + dr * 2; const targetColumn = column + dc * 2; if (middle && middle.c !== piece.c && inBoard(targetRow, targetColumn) && !at(targetRow, targetColumn)) captures.push({ from: [row, column], to: [targetRow, targetColumn], capture: [row + dr, column + dc] }); else if (dr === forward && !middle && inBoard(row + dr, column + dc)) simple.push({ from: [row, column], to: [row + dr, column + dc], capture: null }); }); return capturesOnly ? captures : captures.length ? captures : simple; }
function allMoves(color = game.turn) { const saved = game.turn; game.turn = color; const moves = game.board.flatMap((line, row) => line.flatMap((piece, column) => piece?.c === color ? (game.type === 'chess' ? chessMovesFor(row, column) : checkerMovesFor(row, column, game.type === 'checkers' && hasCheckerCapture(color))) : [])); game.turn = saved; return moves; }
function hasCheckerCapture(color) { const saved = game.turn; game.turn = color; const found = game.board.some((line, row) => line.some((piece, column) => piece?.c === color && checkerMovesFor(row, column, true).length)); game.turn = saved; return found; }
function applyMove(move) { const piece = at(...move.from); if (!piece) return; game.board[move.to[0]][move.to[1]] = piece; game.board[move.from[0]][move.from[1]] = null; if (game.type === 'checkers' && move.capture) game.board[move.capture[0]][move.capture[1]] = null; if (game.type === 'chess' && piece.t === 'p' && (move.to[0] === 0 || move.to[0] === 7)) piece.t = 'q'; game.log.unshift(`${game.turn === 'w' ? 'Vous' : 'Bot'} : ${label(...move.from)} → ${label(...move.to)}${move.capture ? ' ×' : ''}`); game.log = game.log.slice(0, 8); if (game.type === 'checkers' && move.capture && chainCaptures.checked) { game.forced = [...move.to]; const continuation = checkerMovesFor(...move.to, true); if (continuation.length) { game.selected = [...move.to]; game.legal = continuation; statusElement.textContent = game.turn === 'w' ? 'Vous devez poursuivre la prise avec la pièce sélectionnée.' : 'Le bot poursuit sa prise.'; render(); if (game.turn === 'b') scheduleBot(); return; } } if (game.type === 'checkers' && ((piece.c === 'w' && move.to[0] === 0) || (piece.c === 'b' && move.to[0] === 7))) piece.k = true; game.forced = null; game.turn = other(game.turn); game.selected = null; game.legal = []; checkEnd(); render(); if (!game.over && game.turn === 'b') scheduleBot(); }
function checkEnd() { const moves = allMoves(game.turn); if (moves.length) { statusElement.textContent = game.turn === 'w' ? 'À vous de jouer.' : 'Le bot réfléchit.'; return; } game.over = true; statusElement.textContent = game.type === 'chess' ? (game.turn === 'w' ? 'Échec et mat : le bot gagne.' : 'Échec et mat : vous gagnez.') : (game.turn === 'w' ? 'Vous n’avez plus de coup : le bot gagne.' : 'Le bot n’a plus de coup : vous gagnez.'); }
function chooseBotMove() { const moves = game.forced ? checkerMovesFor(...game.forced, true) : allMoves('b'); const level = difficultySelect.value; return moves.sort((first, second) => { const targetFirst = at(...first.to); const targetSecond = at(...second.to); const scoreFirst = (first.capture ? 7 : 0) + (targetFirst ? values[targetFirst.t] : 0) + Math.random() * (level === 'hard' ? 1 : 8); const scoreSecond = (second.capture ? 7 : 0) + (targetSecond ? values[targetSecond.t] : 0) + Math.random() * (level === 'hard' ? 1 : 8); return scoreSecond - scoreFirst; })[0]; }
function scheduleBot() { clearTimeout(botTimer); botTimer = setTimeout(() => { if (!game.over && game.turn === 'b') applyMove(chooseBotMove()); }, difficultySelect.value === 'easy' ? 950 : difficultySelect.value === 'hard' ? 260 : 550); }
function selectCell(row, column) { if (game.over || game.turn !== 'w') return; const selectedMove = game.legal.find(move => move.to[0] === row && move.to[1] === column); if (selectedMove) { applyMove(selectedMove); return; } if (game.forced) { if (row === game.forced[0] && column === game.forced[1]) { game.selected = [...game.forced]; game.legal = checkerMovesFor(...game.forced, true); render(); } return; } const legal = game.type === 'chess' ? chessMovesFor(row, column) : checkerMovesFor(row, column, hasCheckerCapture('w')); if (at(row, column)?.c === 'w' && legal.length) { game.selected = [row, column]; game.legal = legal; render(); } }
function render() { titleElement.textContent = game.type === 'chess' ? 'Échecs' : 'Dames'; rulesElement.textContent = game.type === 'chess' ? 'Déplacez les Blancs. Les coups qui laissent votre roi en échec sont exclus. Roque et prise en passant ne sont pas encore proposés.' : 'Les prises sont obligatoires. Une prise multiple doit être poursuivie ; une pièce devient dame sur la dernière rangée.'; boardElement.innerHTML = game.board.flatMap((line, row) => line.map((piece, column) => { const move = game.legal.find(item => item.to[0] === row && item.to[1] === column); const selected = game.selected?.[0] === row && game.selected?.[1] === column; const content = !piece ? '' : game.type === 'chess' ? `<span class="piece ${piece.c === 'b' ? 'black' : ''}">${glyphs[`${piece.c}${piece.t}`]}</span>` : `<span class="checker ${piece.c === 'b' ? 'black' : ''}${piece.k ? ' king' : ''}"></span>`; return `<button class="cell ${(row + column) % 2 ? 'dark' : ''}${selected ? ' selected' : ''}${move ? (move.capture ? ' capture' : ' legal') : ''}" style="z-index:${row + 1}" data-row="${row}" data-column="${column}">${content}</button>`; })).join(''); boardElement.querySelectorAll('.cell').forEach(cell => cell.addEventListener('click', () => selectCell(Number(cell.dataset.row), Number(cell.dataset.column)))); const white = game.board.flat().filter(piece => piece?.c === 'w').length; const black = game.board.flat().filter(piece => piece?.c === 'b').length; scoreElement.innerHTML = `<div>Vous<br><strong>${white}</strong></div><div>Bot<br><strong>${black}</strong></div>`; historyElement.innerHTML = game.log.map(entry => `<li>${entry}</li>`).join('') || '<li>Déplacez une pièce blanche.</li>'; }
function newGame() { clearTimeout(botTimer); game = { type: typeSelect.value, board: typeSelect.value === 'chess' ? initialChess() : initialCheckers(), turn: 'w', selected: null, legal: [], forced: null, over: false, log: [] }; statusElement.textContent = 'À vous de jouer.'; render(); }
const initialType = new URLSearchParams(location.search).get('variant');
if (!window.GameEffects) { const script = document.createElement('script'); script.src = '../../shared/effects.js?v=1'; document.head.appendChild(script); }
boardElement.addEventListener('click', () => window.GameEffects?.play('move'), true);
if (initialType === 'checkers') typeSelect.value = 'checkers';
document.getElementById('newGame').addEventListener('click', newGame);
typeSelect.addEventListener('change', newGame);
difficultySelect.addEventListener('change', newGame);
localStorage.setItem('game-hub:last-game', 'chess');
newGame();
