'use strict';
const boardElement=document.getElementById('board'),statusElement=document.getElementById('status'),formatSelect=document.getElementById('format'),difficultySelect=document.getElementById('difficulty'),targetSelect=document.getElementById('target');let columns=7,rows=6,cells=[],turn=1,finished=false,winning=[];
function start(){[columns,rows]=formatSelect.value.split('x').map(Number);cells=Array(columns*rows).fill(0);turn=1;finished=false;winning=[];statusElement.textContent='À vous : choisissez une colonne.';render()}
const index=(row,col)=>row*columns+col;function landing(col,source=cells){for(let row=rows-1;row>=0;row--)if(!source[index(row,col)])return index(row,col);return-1}
function winner(source=cells){const target=Number(targetSelect.value),directions=[[0,1],[1,0],[1,1],[1,-1]];for(let row=0;row<rows;row++)for(let col=0;col<columns;col++){const player=source[index(row,col)];if(!player)continue;for(const [dr,dc]of directions){const line=[];for(let step=0;step<target;step++){const r=row+dr*step,c=col+dc*step;if(r<0||r>=rows||c<0||c>=columns||source[index(r,c)]!==player)break;line.push(index(r,c))}if(line.length===target)return{player,line}}}return null}
function play(col,player=1){if(finished||turn!==player)return false;const targetIndex=landing(col);if(targetIndex<0)return false;cells[targetIndex]=player;const result=winner();if(result){finished=true;winning=result.line;statusElement.textContent=player===1?'Vous gagnez !':'Le bot gagne.';window.GameRecords?.finish({score:player===1?100:0,scoreLabel:player===1?'Victoire':'Défaite',won:player===1});render();return true}if(cells.every(Boolean)){finished=true;statusElement.textContent='Match nul.';render();return true}turn=player===1?2:1;render();if(turn===2)setTimeout(botPlay,260);return true}
function botPlay(){if(finished)return;const legal=Array.from({length:columns},(_,col)=>col).filter(col=>landing(col)>=0);const winMove=legal.find(col=>{const copy=[...cells];copy[landing(col,copy)]=2;return winner(copy)?.player===2});const blockMove=legal.find(col=>{const copy=[...cells];copy[landing(col,copy)]=1;return winner(copy)?.player===1});const center=[...legal].sort((a,b)=>Math.abs(a-(columns-1)/2)-Math.abs(b-(columns-1)/2));const chance={easy:.25,normal:.65,hard:.9,expert:1}[difficultySelect.value];const choice=Math.random()<chance?(winMove??blockMove??center[0]):legal[Math.floor(Math.random()*legal.length)];play(choice,2)}
function render(){boardElement.style.setProperty('--columns',columns);boardElement.replaceChildren(...cells.map((value,cellIndex)=>{const button=document.createElement('button');button.type='button';button.className=`slot${value===1?' red':value===2?' yellow':''}${winning.includes(cellIndex)?' win':''}`;button.setAttribute('aria-label',`Colonne ${cellIndex%columns+1}`);button.onclick=()=>play(cellIndex%columns);return button}))}
document.getElementById('newGame').onclick=start;formatSelect.onchange=start;targetSelect.onchange=start;start();window.ConnectFourTestAPI={diagnostics:()=>({columns,rows,target:Number(targetSelect.value),slots:cells.length,legal:Array.from({length:columns},(_,col)=>landing(col)).filter(value=>value>=0).length})};
