'use strict';
const boardElement=document.getElementById('board'),statusElement=document.getElementById('status'),formatSelect=document.getElementById('format'),difficultySelect=document.getElementById('difficulty'),targetSelect=document.getElementById('target');let columns=7,rows=6,cells=[],turn=1,finished=false,winning=[],lastMove=-1;const motionStyle=document.createElement('style');motionStyle.textContent='.slot.dropped{animation:align-drop .32s cubic-bezier(.2,.8,.35,1.25)}@keyframes align-drop{0%{transform:translateY(-180%);filter:brightness(1.5)}100%{transform:none}}';document.head.appendChild(motionStyle);
function start(){[columns,rows]=formatSelect.value.split('x').map(Number);cells=Array(columns*rows).fill(0);turn=1;finished=false;winning=[];lastMove=-1;statusElement.textContent='À vous : choisissez une colonne.';render()}
const index=(row,col)=>row*columns+col;function landing(col,source=cells){for(let row=rows-1;row>=0;row--)if(!source[index(row,col)])return index(row,col);return-1}
function winner(source=cells){const target=Number(targetSelect.value),directions=[[0,1],[1,0],[1,1],[1,-1]];for(let row=0;row<rows;row++)for(let col=0;col<columns;col++){const player=source[index(row,col)];if(!player)continue;for(const [dr,dc]of directions){const line=[];for(let step=0;step<target;step++){const r=row+dr*step,c=col+dc*step;if(r<0||r>=rows||c<0||c>=columns||source[index(r,c)]!==player)break;line.push(index(r,c))}if(line.length===target)return{player,line}}}return null}
function play(col,player=1){if(finished||turn!==player)return false;const targetIndex=landing(col);if(targetIndex<0)return false;cells[targetIndex]=player;lastMove=targetIndex;const result=winner();if(result){finished=true;winning=result.line;statusElement.textContent=player===1?'Vous gagnez !':'Le bot gagne.';window.GameRecords?.finish({score:player===1?100:0,scoreLabel:player===1?'Victoire':'Défaite',won:player===1});render();return true}if(cells.every(Boolean)){finished=true;statusElement.textContent='Match nul.';render();return true}turn=player===1?2:1;render();if(turn===2)setTimeout(botPlay,320);return true}
function orderedLegal(source){return Array.from({length:columns},(_,column)=>column).filter(column=>landing(column,source)>=0).sort((left,right)=>Math.abs(left-(columns-1)/2)-Math.abs(right-(columns-1)/2));}
function windowScore(values){const bot=values.filter(value=>value===2).length,human=values.filter(value=>value===1).length,empty=values.length-bot-human;if(bot&&human)return 0;if(bot===values.length)return 100000;if(human===values.length)return-100000;if(bot)return bot**3*(empty===1?7:1);if(human)return-(human**3)*(empty===1?8:1);return 0;}
function evaluate(source){let score=0;for(let row=0;row<rows;row++)for(let col=0;col<columns;col++){const value=source[index(row,col)];if(value)score+=(value===2?1:-1)*(columns-Math.abs(col-(columns-1)/2));for(const[dr,dc]of [[0,1],[1,0],[1,1],[1,-1]]){const values=[];for(let step=0;step<Number(targetSelect.value);step++){const r=row+dr*step,c=col+dc*step;if(r<0||r>=rows||c<0||c>=columns){values.length=0;break;}values.push(source[index(r,c)]);}if(values.length)score+=windowScore(values);}}return score;}
function search(source,player,depth,alpha,beta){const result=winner(source);if(result)return result.player===2?1000000+depth:-1000000-depth;const legal=orderedLegal(source);if(!depth||!legal.length)return evaluate(source);if(player===2){let best=-Infinity;for(const column of legal){const copy=[...source];copy[landing(column,copy)]=2;best=Math.max(best,search(copy,1,depth-1,alpha,beta));alpha=Math.max(alpha,best);if(beta<=alpha)break;}return best;}let best=Infinity;for(const column of legal){const copy=[...source];copy[landing(column,copy)]=1;best=Math.min(best,search(copy,2,depth-1,alpha,beta));beta=Math.min(beta,best);if(beta<=alpha)break;}return best;}
function botPlay(){if(finished||turn!==2)return;const legal=orderedLegal(cells);if(!legal.length)return;const winMove=legal.find(column=>{const copy=[...cells];copy[landing(column,copy)]=2;return winner(copy)?.player===2});const blockMove=legal.find(column=>{const copy=[...cells];copy[landing(column,copy)]=1;return winner(copy)?.player===1});let choice;if(difficultySelect.value==='easy')choice=Math.random()<.45?(winMove??blockMove??legal[0]):legal[Math.floor(Math.random()*legal.length)];else{const baseDepth={normal:2,hard:4,expert:5}[difficultySelect.value]||2,depth=Math.max(2,baseDepth-(columns>=10?1:0));const ranked=legal.map(column=>{const copy=[...cells];copy[landing(column,copy)]=2;return{column,score:search(copy,1,depth-1,-Infinity,Infinity)};}).sort((left,right)=>right.score-left.score);choice=difficultySelect.value==='normal'&&ranked.length>1&&Math.random()<.2?ranked[1].column:ranked[0].column;}play(choice,2)}
function render(){boardElement.style.setProperty('--columns',columns);boardElement.replaceChildren(...cells.map((value,cellIndex)=>{const button=document.createElement('button');button.type='button';button.className=`slot${value===1?' red':value===2?' yellow':''}${winning.includes(cellIndex)?' win':''}${lastMove===cellIndex?' dropped':''}`;button.setAttribute('aria-label',`Colonne ${cellIndex%columns+1}`);button.onclick=()=>play(cellIndex%columns);return button}))}
document.getElementById('newGame').onclick=start;formatSelect.onchange=start;targetSelect.onchange=start;start();window.ConnectFourTestAPI={diagnostics:()=>({columns,rows,target:Number(targetSelect.value),slots:cells.length,legal:Array.from({length:columns},(_,col)=>landing(col)).filter(value=>value>=0).length,search:typeof search==='function',evaluation:evaluate(cells)})};
