const stage=document.getElementById('stage');
const statusElement=document.getElementById('status');
const pairsElement=document.getElementById('pairs');
const freeElement=document.getElementById('free');
const faces=[...Array.from({length:9},(_,index)=>({id:`man${index+1}`,label:`${index+1}萬`,family:'man'})),...Array.from({length:9},(_,index)=>({id:`pin${index+1}`,label:`${index+1}●`,family:'pin'})),...Array.from({length:9},(_,index)=>({id:`sou${index+1}`,label:`${index+1}竹`,family:'sou'})),...['東','南','西','北'].map((label,index)=>({id:`wind${index}`,label,family:'honor'})),...['中','發','白'].map((label,index)=>({id:`dragon${index}`,label,family:'dragon'})),...['🌸','🌼'].map((label,index)=>({id:`flower${index}`,label,family:'flower'}))];
let game;
function shuffle(values){const result=values.slice();for(let index=result.length-1;index>0;index-=1){const other=Math.floor(Math.random()*(index+1));[result[index],result[other]]=[result[other],result[index]]}return result}
function createLayout(){const positions=[];const rows=[[3,8],[1,10],[0,11],[0,11],[1,10],[3,8]];let id=0;rows.forEach(([start,end],row)=>{for(let column=start;column<=end;column+=1)positions.push({id:id++,x:column,y:row,z:0})});for(let row=2;row<=3;row+=1)for(let column=3;column<=8;column+=1)positions.push({id:id++,x:column,y:row,z:1});for(let row=2;row<=3;row+=1)for(let column=5;column<=6;column+=1)positions.push({id:id++,x:column,y:row,z:2});return positions}
function occupiedMap(ids){return new Map([...ids].map(id=>[id,game.positions.find(position=>position.id===id)]))}
function freePosition(position, ids){const occupied=occupiedMap(ids);const covered=[...occupied.values()].some(other=>other.z>position.z&&Math.abs(other.x-position.x)<=1&&Math.abs(other.y-position.y)<=1);if(covered)return false;const left=[...occupied.values()].some(other=>other.z===position.z&&other.y===position.y&&other.x===position.x-1);const right=[...occupied.values()].some(other=>other.z===position.z&&other.y===position.y&&other.x===position.x+1);return !left||!right}
function solvableAssignment(){for(let attempt=0;attempt<80;attempt+=1){const remaining=new Set(game.positions.map(position=>position.id)),pairs=[];let valid=true;while(remaining.size){const free=shuffle(game.positions.filter(position=>remaining.has(position.id)&&freePosition(position,remaining)));if(free.length<2){valid=false;break}const pair=[free[0],free[1]];pair.forEach(position=>remaining.delete(position.id));pairs.push(pair)}if(valid)return pairs}throw new Error('Impossible de construire un ordre de retrait valide. Réessayez.');}
function newGame(){game={positions:createLayout(),tiles:new Map(),removed:new Set(),selected:null,history:[],hint:[],solution:[]};const pairs=solvableAssignment();const values=shuffle(faces);pairs.forEach((pair,index)=>{game.solution.push(pair.map(position=>position.id));pair.forEach(position=>game.tiles.set(position.id,{...values[index],pair:index}))});statusElement.textContent='Plateau vérifié : les 72 tuiles forment 36 paires et possèdent un ordre de retrait garanti.';render()}
function isFree(id){return !game.removed.has(id)&&freePosition(game.positions.find(position=>position.id===id),new Set(game.positions.map(position=>position.id).filter(positionId=>!game.removed.has(positionId))))}
function matching(left,right){return left.id===right.id}
function choose(id){if(game.removed.has(id)||!isFree(id))return;const tile=game.tiles.get(id);if(game.selected===id){game.selected=null;render();return}if(game.selected===null){game.selected=id;render();return}const selectedTile=game.tiles.get(game.selected);if(!matching(selectedTile,tile)){game.selected=id;statusElement.textContent='Ces tuiles ne correspondent pas : choisissez une autre tuile libre.';render();return}const pair=[game.selected,id];game.removed.add(pair[0]);game.removed.add(pair[1]);game.history.push(pair);game.selected=null;game.hint=[];window.GameEffects?.play('success');if(game.removed.size===game.positions.length){statusElement.textContent='Mahjong ! Le plateau est entièrement vidé.';window.GameEffects?.play('win')}else statusElement.textContent='Paire retirée. De nouvelles tuiles peuvent être libres.';render()}
function availablePairs(){const free=game.positions.filter(position=>isFree(position.id));const pairs=[];for(let index=0;index<free.length;index+=1)for(let other=index+1;other<free.length;other+=1)if(matching(game.tiles.get(free[index].id),game.tiles.get(free[other].id)))pairs.push([free[index].id,free[other].id]);return pairs}
function solveRemaining(){const initial=new Set(game.positions.map(position=>position.id).filter(id=>!game.removed.has(id)));const memo=new Set();let visits=0;function search(remaining){if(!remaining.size)return[];if(visits++>180000)return null;const key=[...remaining].sort((left,right)=>left-right).join(',');if(memo.has(key))return null;const free=game.positions.filter(position=>remaining.has(position.id)&&freePosition(position,remaining));const byFace=new Map();free.forEach(position=>{const face=game.tiles.get(position.id).id;if(!byFace.has(face))byFace.set(face,[]);byFace.get(face).push(position.id)});const candidates=[];byFace.forEach(ids=>{for(let index=0;index<ids.length;index+=1)for(let other=index+1;other<ids.length;other+=1)candidates.push([ids[index],ids[other]])});candidates.sort((left,right)=>{const known=game.solution.findIndex(pair=>pair.includes(left[0])&&pair.includes(left[1]));const otherKnown=game.solution.findIndex(pair=>pair.includes(right[0])&&pair.includes(right[1]));return(otherKnown<0)-(known<0)||known-otherKnown});for(const pair of candidates){const next=new Set(remaining);pair.forEach(id=>next.delete(id));const continuation=search(next);if(continuation)return[pair,...continuation]}memo.add(key);return null}return search(initial)}
function hint(){const solution=solveRemaining();const pair=solution?.[0];if(!pair){statusElement.textContent=availablePairs().length?'Les coups libres actuels mènent à une impasse détectée : annulez un coup.':'Aucune paire libre : annulez un coup ou recommencez le plateau.';window.GameEffects?.play('error');return}game.hint=pair;statusElement.textContent=`Indice vérifié : cette paire ouvre une solution complète de ${solution.length} étape(s).`;render()}
function solveStep(){const pair=solveRemaining()?.[0];if(!pair){statusElement.textContent='Aucune continuation complète trouvée : annulez un coup ou recommencez.';return}game.selected=null;choose(pair[0]);choose(pair[1]);}
function undo(){const pair=game.history.pop();if(!pair)return;pair.forEach(id=>game.removed.delete(id));game.selected=null;game.hint=[];statusElement.textContent='Dernière paire restaurée.';render()}
function render(){const free=game.positions.filter(position=>isFree(position.id));pairsElement.textContent=String(game.removed.size/2);freeElement.textContent=String(free.length);stage.innerHTML=game.positions.filter(position=>!game.removed.has(position.id)).sort((left,right)=>left.z-right.z).map(position=>{const tile=game.tiles.get(position.id);const classes=`tile ${tile.family}${isFree(position.id)?' free':' locked'}${game.selected===position.id?' selected':''}${game.hint.includes(position.id)?' hint':''}`;const left=52+position.x*52+position.z*5;const top=60+position.y*67-position.z*15;return`<button class="${classes}" style="left:${left}px;top:${top}px;z-index:${position.z*10+position.y}" data-id="${position.id}">${tile.label}</button>`}).join('');stage.querySelectorAll('[data-id]').forEach(button=>button.onclick=()=>choose(Number(button.dataset.id)))}
document.getElementById('hint').insertAdjacentHTML('afterend','<button id="solve">Résoudre une paire</button>');document.head.insertAdjacentHTML('beforeend','<style>.tile.sou{color:#15803d}.tile.honor{color:#7c3aed}.tile.dragon{color:#dc2626}.tile.flower{color:#db2777;font-size:25px}</style>');document.getElementById('newGame').onclick=newGame;document.getElementById('hint').onclick=hint;document.getElementById('solve').onclick=solveStep;document.getElementById('undo').onclick=undo;if(!window.GameEffects){const script=document.createElement('script');script.src='../../shared/effects.js?v=1';document.head.appendChild(script)}localStorage.setItem('game-hub:last-game','mahjong');newGame();
