const boardElement=document.getElementById('board'),modeSelect=document.getElementById('mode'),previewElement=document.getElementById('preview'),statusElement=document.getElementById('status'),scoreElement=document.getElementById('score');
const defs={terrain:{title:'Territoires',desc:'Posez des tuiles de terre, d’eau et de route pour former les plus grands ensembles.',rules:['Placez une tuile près d’une tuile existante.','Les groupes de même terrain adjacents rapportent des points.','Une route longue rapporte un bonus.'],tiles:['terrain','water','road']},mosaic:{title:'Mosaïque',desc:'Complétez des lignes et colonnes de quatre couleurs sans répétition.',rules:['Posez la couleur indiquée sur une case vide.','Une couleur ne peut pas se répéter dans une ligne ou colonne.','Les lignes complètes rapportent 10 points.'],tiles:['mosaic-red','mosaic-blue','mosaic-yellow','mosaic-green']},routes:{title:'Routes',desc:'Étendez trois itinéraires colorés sur le plateau.',rules:['Chaque route doit prolonger sa propre couleur.','Atteindre un bord différent rapporte un bonus.','Les routes ne se croisent pas.'],tiles:['route-a','route-b','route-c']}};
let state={},randomGenerator=Math.random;const random=()=>randomGenerator();const neighbors=index=>[index-6,index+6,index%6?index-1:-1,index%6<5?index+1:-1].filter(value=>value>=0&&value<36);
function nextTile(){const tiles=defs[modeSelect.value].tiles;state.tile=tiles[Math.floor(random()*tiles.length)];state.rotation=(state.rotation||0)%4;}
function newGame(){randomGenerator=window.GameRuntime?.createRandom(`${new URLSearchParams(location.search).get('seed')||Date.now()}:${modeSelect.value}`)||Math.random;state={cells:Array(36).fill(null),tile:null,rotation:0,score:0,turn:1,placed:false};if(modeSelect.value==='terrain')state.cells[17]='terrain';if(modeSelect.value==='routes'){state.cells[0]='route-a';state.cells[5]='route-b';state.cells[30]='route-c';}nextTile();statusElement.textContent='Choisissez une case pour poser la tuile.';render();}
function allowed(index){if(state.cells[index])return false;const mode=modeSelect.value;if(mode==='terrain')return neighbors(index).some(other=>state.cells[other]);if(mode==='mosaic'){const row=Math.floor(index/6),col=index%6;return !state.cells.some((tile,position)=>tile===state.tile&&(Math.floor(position/6)===row||position%6===col));}return neighbors(index).some(other=>state.cells[other]===state.tile);}
function place(index){if(state.placed||!allowed(index)){statusElement.textContent='Cette pose ne respecte pas les contraintes du mode.';return;}state.cells[index]=state.tile;state.lastIndex=index;state.placed=true;statusElement.textContent='Tuile posée : validez le tour.';render();}
function groupSize(index){const tile=state.cells[index],seen=new Set([index]),queue=[index];while(queue.length){const current=queue.shift();neighbors(current).forEach(other=>{if(!seen.has(other)&&state.cells[other]===tile){seen.add(other);queue.push(other);}});}return seen.size;}
function validateTurn(){if(!state.placed){statusElement.textContent='Posez d’abord la tuile disponible.';return;}const index=state.lastIndex;let gain=groupSize(index);if(modeSelect.value==='mosaic'){const row=Math.floor(index/6),col=index%6;gain=(state.cells.filter((tile,position)=>Math.floor(position/6)===row).every(Boolean)?10:0)+(state.cells.filter((tile,position)=>position%6===col).every(Boolean)?10:0)+1;}if(modeSelect.value==='routes'){gain+=neighbors(index).filter(other=>state.cells[other]===state.tile).length*3;if(index<6||index>29||index%6===0||index%6===5)gain+=8;}state.score+=gain;state.turn++;state.placed=false;if(state.cells.every(Boolean)||state.turn>24){statusElement.textContent=`Partie terminée : ${state.score} points.`;window.GameRecords?.finish({score:state.score,scoreLabel:'Points',won:true});}else{nextTile();statusElement.textContent=`+${gain} point${gain>1?'s':''}. Tour ${state.turn}.`;}render();}
function render(){const def=defs[modeSelect.value];document.getElementById('title').textContent=def.title;document.getElementById('description').textContent=def.desc;document.getElementById('rules').innerHTML=def.rules.map(rule=>`<li>${rule}</li>`).join('');previewElement.textContent=state.tile?.replace('mosaic-','').replace('route-','Route ').replace('terrain','Terre').replace('water','Eau').replace('road','Route')||'';previewElement.className=`preview ${state.tile||''}`;scoreElement.textContent=`${state.score} points · tour ${state.turn}`;document.getElementById('rotate').hidden=state.tile!=='road';boardElement.replaceChildren(...state.cells.map((tile,index)=>{const cell=document.createElement('button');cell.className=`cell ${tile||'empty'}`;cell.disabled=Boolean(tile)||state.placed;cell.onclick=()=>place(index);if(modeSelect.value==='routes'&&tile)cell.innerHTML='<i class="token"></i>';return cell;}));}
document.getElementById('newGame').onclick=newGame;document.getElementById('rotate').onclick=()=>{state.rotation=(state.rotation+1)%4;statusElement.textContent=`Tuile orientée à ${state.rotation*90}°.`;previewElement.style.transform=`rotate(${state.rotation*90}deg)`;};document.getElementById('confirm').onclick=validateTurn;document.getElementById('hint').onclick=()=>{const index=state.cells.findIndex((tile,position)=>!tile&&allowed(position));statusElement.textContent=index<0?'Aucune pose légale : recommencez.':`Conseil : essayez la case ${index+1}.`;};modeSelect.onchange=newGame;newGame();window.TilesRoutesTestAPI={diagnostics:()=>({modes:Object.keys(defs),cells:state.cells.length,preview:Boolean(state.tile),controls:['confirm','hint','rotate'].every(id=>document.getElementById(id))})};try{localStorage.setItem('game-hub:last-game','tiles-routes');}catch{}
