'use strict';
const icons={animals:['🐶','🐱','🦊','🐼','🐸','🦁','🐵','🐙','🦋','🐢','🦉','🐝','🐬','🦖','🐘','🦒','🐧','🦀'],food:['🍎','🍓','🍋','🍉','🥕','🍕','🍪','🍩','🍒','🥝','🧀','🥐','🍇','🌮','🍰','🥑','🍄','🥨'],music:['🎺','🎷','🥁','🎸','🎻','🎹','🪕','🪇','🎤','🎧','🎵','🎼','🪈','📯','🪘','🎶','🔔','🎙️']};
const boardElement=document.getElementById('board'),statusElement=document.getElementById('status'),scoreElement=document.getElementById('score'),pairsSelect=document.getElementById('pairs'),difficultySelect=document.getElementById('difficulty'),themeSelect=document.getElementById('theme');let cards=[],opened=[],scores=[0,0],turn=0,busy=false,memory=new Map(),random=Math.random,gameIndex=0,lanPaused=false;
function schedule(action,delay){setTimeout(()=>{if(lanPaused)schedule(action,100);else action()},delay)}
function shuffle(values){return window.GameRuntime?.shuffle(values,random)||values.sort(()=>random()-.5)}function start(){const count=Number(pairsSelect.value),sharedSeed=new URLSearchParams(location.search).get('seed');random=window.GameRuntime?.createRandom(`memory:${sharedSeed||Date.now()}:${sharedSeed?0:gameIndex++}`)||Math.random;cards=shuffle([...icons[themeSelect.value].slice(0,count),...icons[themeSelect.value].slice(0,count)]).map((symbol,index)=>({id:index,symbol,open:false,matched:false}));opened=[];scores=[0,0];turn=0;busy=false;lanPaused=false;memory.clear();window.GameRecords?.reset();statusElement.textContent='À vous de retourner deux cartes.';render()}
function choose(index,bot=false){const card=cards[index];if(busy||card.open||card.matched||(!bot&&turn===1))return;card.open=true;opened.push(index);memory.set(card.symbol,[...(memory.get(card.symbol)||[]).filter(other=>!cards[other].matched),index]);render();if(opened.length===2){busy=true;schedule(resolvePair,650)}}
function resolvePair(){const[first,second]=opened;if(cards[first].symbol===cards[second].symbol){cards[first].matched=cards[second].matched=true;scores[turn]++;statusElement.textContent=turn===0?'Paire trouvée, rejouez.':'Le bot trouve une paire et rejoue.'}else{cards[first].open=cards[second].open=false;turn=difficultySelect.value==='none'?0:turn?0:1;statusElement.textContent=turn===0?'À vous.':'Le bot mémorise et joue.'}opened=[];busy=false;render();if(cards.every(card=>card.matched)){const won=scores[0]>=scores[1];statusElement.textContent=scores[0]===scores[1]?'Égalité.':won?'Vous gagnez !':'Le bot gagne.';window.GameRecords?.finish({score:scores[0]*100,scoreLabel:`${scores[0]} paire(s)`,won});return}if(turn===1)schedule(botPlay,550)}
function botPlay(){if(turn!==1||busy)return;const remembered=[...memory.values()].find(indexes=>indexes.filter(index=>!cards[index].matched&&!cards[index].open).length>=2);const chance={easy:.2,normal:.6,hard:1}[difficultySelect.value]??0;if(remembered&&random()<chance){const choices=remembered.filter(index=>!cards[index].matched&&!cards[index].open).slice(0,2);choose(choices[0],true);schedule(()=>choose(choices[1],true),300);return}const hidden=cards.map((card,index)=>!card.open&&!card.matched?index:-1).filter(index=>index>=0);choose(hidden[Math.floor(random()*hidden.length)],true);schedule(()=>{const remaining=cards.map((card,index)=>!card.open&&!card.matched?index:-1).filter(index=>index>=0);choose(remaining[Math.floor(random()*remaining.length)],true)},300)}
function render(){const columns=cards.length<=12?4:cards.length<=24?6:8;boardElement.style.setProperty('--columns',columns);boardElement.replaceChildren(...cards.map((card,index)=>{const button=document.createElement('button');button.className=`card${card.open?' open':''}${card.matched?' matched':''}`;button.textContent=card.open||card.matched?card.symbol:'?';button.onclick=()=>choose(index);return button}));scoreElement.textContent=`Vous ${scores[0]} · ${difficultySelect.value==='none'?'Solo':`Bot ${scores[1]}`}`}
document.getElementById('newGame').onclick=start;pairsSelect.onchange=start;themeSelect.onchange=start;difficultySelect.onchange=()=>{start();if(difficultySelect.value==='none')turn=0};start();window.addEventListener('lan:start',start);window.addEventListener('lan:pause',event=>{lanPaused=Boolean(event.detail?.paused)});window.MemoryTestAPI={diagnostics:()=>({cards:cards.length,pairs:cards.length/2,unique:new Set(cards.map(card=>card.symbol)).size,columns:Number(boardElement.style.getPropertyValue('--columns'))})};
