'use strict';
const canvas=document.getElementById('screen'),context=canvas.getContext('2d'),difficultySelect=document.getElementById('difficulty'),courseSelect=document.getElementById('course'),goalSelect=document.getElementById('goal'),statusElement=document.getElementById('status');
const COLS=12,ROWS=13,CELL=60,directions={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]},keyMap={ArrowUp:'up',z:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',q:'left',a:'left',ArrowRight:'right',d:'right'};
const difficulties={easy:{speed:.72,density:.72,lives:6},normal:{speed:1,density:1,lives:4},hard:{speed:1.23,density:1.16,lives:3},extreme:{speed:1.48,density:1.3,lives:2}};
let game=null,running=false,paused=false,frame=0,last=0;
function randomFor(seed){return window.GameRuntime?.createRandom(`crossing:${seed}`)||Math.random;}
function laneKind(row,random){if(row===0||row===6||row===12)return'safe';if(courseSelect.value==='city')return row<6&&random()<.2?'river':'road';if(courseSelect.value==='delta')return row>6&&random()<.2?'road':'river';return row<6?'river':'road';}
function createLane(row,random,level){const kind=laneKind(row,random);if(kind==='safe')return{kind,row,direction:0,speed:0,items:[]};const direction=random()<.5?-1:1,speed=(42+random()*45+level*4)*difficulties[difficultySelect.value].speed;const width=kind==='river'?2+Math.floor(random()*3):1+Math.floor(random()*2);const gap=Math.max(2.4,width+(3.2-random()*1.4)/difficulties[difficultySelect.value].density);const items=[];for(let x=-width;x<COLS+width;x+=gap)items.push({x:x+random()*.45,width});return{kind,row,direction,speed,items};}
function createGame(seed=`${Date.now()}:${Math.random()}`){const random=randomFor(seed),level=1;return{random,level,lanes:Array.from({length:ROWS},(_,row)=>createLane(row,random,level)),player:{x:5.5,y:12,move:null,invincible:0},homes:new Set(),score:0,crossings:0,lives:difficulties[difficultySelect.value].lives,combo:1,time:0,slow:0,bonus:{x:2+Math.floor(random()*8),y:6,active:true},particles:[],completed:false};}
function start(){cancelAnimationFrame(frame);game=createGame(new URLSearchParams(location.search).get('seed'));running=true;paused=false;document.getElementById('overlay').hidden=true;statusElement.textContent='Trouvez le rythme de chaque voie.';window.GameRecords?.reset();last=performance.now();updateHud();draw();frame=requestAnimationFrame(loop);}
function requestMove(dir){if(!game||paused||game.completed||game.player.move)return;const[dx,dy]=directions[dir];const targetX=game.player.x+dx,targetY=game.player.y+dy;if(targetX<0||targetX>=COLS||targetY<0||targetY>=ROWS)return;game.player.move={fromX:game.player.x,fromY:game.player.y,toX:targetX,toY:targetY,t:0};}
function resetPlayer(message){game.player={x:5.5,y:12,move:null,invincible:1.2};game.lives--;game.combo=1;statusElement.textContent=message;if(game.lives<=0)finish(false,'Vous n’avez plus de véhicules de secours.');}
function arrive(){const slot=Math.max(0,Math.min(4,Math.floor(game.player.x/2.4)));if(game.homes.has(slot)){resetPlayer('Cet emplacement est déjà occupé.');return;}game.homes.add(slot);game.crossings++;game.score+=1000*game.combo+Math.round(500*Math.max(0,1-game.time%14/14));game.combo=Math.min(8,game.combo+1);game.particles.push({x:game.player.x,y:.7,text:`ARRIVÉE ×${game.combo-1}`,life:1.3});game.player={x:5.5,y:12,move:null,invincible:.8};if(game.homes.size===5){game.level++;game.homes.clear();game.lanes=Array.from({length:ROWS},(_,row)=>createLane(row,game.random,game.level));game.score+=2500*game.level;statusElement.textContent=`Parcours ${game.level} : toutes les voies accélèrent.`;}else statusElement.textContent=`Emplacement sécurisé ${game.homes.size}/5.`;const target=goalSelect.value==='endless'?Infinity:Number(goalSelect.value);if(game.crossings>=target)finish(true,'Objectif de traversées atteint !');}
function update(delta){if(!game||game.completed)return;game.time+=delta;game.slow=Math.max(0,game.slow-delta);game.player.invincible=Math.max(0,game.player.invincible-delta);const slowFactor=game.slow?0.48:1;for(const lane of game.lanes){for(const item of lane.items){item.x+=lane.direction*lane.speed*slowFactor*delta/CELL;const margin=item.width+1;if(item.x>COLS+margin)item.x=-margin;if(item.x+item.width<-margin)item.x=COLS+margin;}}
 if(game.player.move){game.player.move.t=Math.min(1,game.player.move.t+delta*8);const move=game.player.move,eased=1-(1-move.t)**3;game.player.x=move.fromX+(move.toX-move.fromX)*eased;game.player.y=move.fromY+(move.toY-move.fromY)*eased;if(move.t>=1){game.player.x=move.toX;game.player.y=move.toY;game.player.move=null;if(game.player.y===0)arrive();}}
 const row=Math.round(game.player.y),lane=game.lanes[row];if(!game.player.move&&lane&&lane.kind!=='safe'){const supporting=lane.items.find(item=>game.player.x+.32>item.x&&game.player.x-.32<item.x+item.width);if(lane.kind==='road'&&supporting&&game.player.invincible<=0)resetPlayer('Collision avec un véhicule !');if(lane.kind==='river'){if(!supporting&&game.player.invincible<=0)resetPlayer('Le courant vous emporte !');else if(supporting){game.player.x+=lane.direction*lane.speed*slowFactor*delta/CELL;if(game.player.x<-.4||game.player.x>COLS-.6)resetPlayer('La plateforme quitte la rive.');}}}
 if(game.bonus.active&&Math.hypot(game.player.x-game.bonus.x,game.player.y-game.bonus.y)<.55){game.bonus.active=false;game.slow=7;game.score+=600;statusElement.textContent='Capsule temporelle : trafic ralenti !';}
 game.particles.forEach(p=>p.life-=delta);game.particles=game.particles.filter(p=>p.life>0);updateHud();}
function finish(won,reason){game.completed=true;running=false;document.getElementById('overlayTitle').textContent=won?'Traversée accomplie':'Fin de parcours';document.getElementById('overlayText').textContent=`${reason} Score : ${game.score.toLocaleString('fr-FR')}.`;document.getElementById('overlay').hidden=false;window.GameRecords?.finish({score:game.score,scoreLabel:`${game.score.toLocaleString('fr-FR')} points`,won});}
function updateHud(){document.getElementById('score').textContent=game.score.toLocaleString('fr-FR');document.getElementById('crossings').textContent=game.crossings;document.getElementById('lives').textContent=game.lives;document.getElementById('combo').textContent=`×${game.combo}`;}
function roundedRect(x,y,w,h,r){context.beginPath();context.roundRect(x,y,w,h,r);context.fill();}
function draw(){context.clearRect(0,0,canvas.width,canvas.height);if(!game)return;for(const lane of game.lanes){const y=lane.row*CELL;if(lane.kind==='safe'){context.fillStyle=lane.row===0?'#14532d':'#166534';context.fillRect(0,y,canvas.width,CELL);for(let x=0;x<COLS;x++){context.fillStyle=(x+lane.row)%2?'#22c55e22':'#86efac18';context.fillRect(x*CELL,y,CELL,CELL);}}else if(lane.kind==='road'){context.fillStyle='#273445';context.fillRect(0,y,canvas.width,CELL);context.strokeStyle='#f8fafc66';context.setLineDash([22,20]);context.beginPath();context.moveTo(0,y+CELL/2);context.lineTo(canvas.width,y+CELL/2);context.stroke();context.setLineDash([]);}else{const water=context.createLinearGradient(0,y,0,y+CELL);water.addColorStop(0,'#075985');water.addColorStop(1,'#0e7490');context.fillStyle=water;context.fillRect(0,y,canvas.width,CELL);context.strokeStyle='#67e8f933';for(let wave=10;wave<CELL;wave+=18){context.beginPath();context.moveTo(0,y+wave);context.lineTo(canvas.width,y+wave);context.stroke();}}
 for(const item of lane.items){const x=item.x*CELL,w=item.width*CELL;if(lane.kind==='road'){context.fillStyle=lane.direction>0?'#fb7185':'#fbbf24';context.shadowColor='#000';context.shadowBlur=6;roundedRect(x+4,y+10,w-8,CELL-20,9);context.shadowBlur=0;context.fillStyle='#dbeafe';context.fillRect(x+lane.direction*(w*.18)+(lane.direction<0?w*.62:0),y+16,w*.2,CELL-32);context.fillStyle='#111827';context.fillRect(x+8,y+5,12,8);context.fillRect(x+w-20,y+5,12,8);context.fillRect(x+8,y+CELL-13,12,8);context.fillRect(x+w-20,y+CELL-13,12,8);}else{context.fillStyle='#854d0e';roundedRect(x,y+9,w,CELL-18,15);context.strokeStyle='#facc1538';for(let mark=18;mark<w;mark+=28){context.beginPath();context.moveTo(x+mark,y+12);context.lineTo(x+mark,y+CELL-12);context.stroke();}}}}
 context.fillStyle='#052e16';for(let slot=0;slot<5;slot++){const x=(slot*2.4+.25)*CELL;context.strokeStyle=game.homes.has(slot)?'#facc15':'#86efac';context.lineWidth=4;context.beginPath();context.arc(x+CELL*.8,CELL*.5,CELL*.32,0,Math.PI*2);context.stroke();if(game.homes.has(slot)){context.fillStyle='#facc15';context.beginPath();context.arc(x+CELL*.8,CELL*.5,CELL*.2,0,Math.PI*2);context.fill();}}
 if(game.bonus.active){context.fillStyle='#e879f9';context.shadowColor='#f0abfc';context.shadowBlur=14;context.beginPath();context.arc((game.bonus.x+.5)*CELL,(game.bonus.y+.5)*CELL,14+Math.sin(game.time*5)*2,0,Math.PI*2);context.fill();context.shadowBlur=0;}
 const px=(game.player.x+.5)*CELL,py=(game.player.y+.5)*CELL;context.save();context.translate(px,py);context.globalAlpha=game.player.invincible>0&&Math.floor(game.time*12)%2?.4:1;context.fillStyle='#f8fafc';context.shadowColor='#4ade80';context.shadowBlur=12;context.beginPath();context.arc(0,0,20,0,Math.PI*2);context.fill();context.fillStyle='#16a34a';context.beginPath();context.arc(-7,-3,5,0,Math.PI*2);context.arc(7,-3,5,0,Math.PI*2);context.fill();context.fillRect(-15,8,30,7);context.restore();context.globalAlpha=1;
 game.particles.forEach(p=>{context.globalAlpha=p.life;context.fillStyle='#fef08a';context.font='900 25px Arial';context.textAlign='center';context.fillText(p.text,(p.x+.5)*CELL,(p.y+.5)*CELL);});context.globalAlpha=1;if(paused){context.fillStyle='#021710bb';context.fillRect(0,0,canvas.width,canvas.height);context.fillStyle='#fff';context.font='900 52px Arial';context.textAlign='center';context.fillText('PAUSE',canvas.width/2,canvas.height/2);}}
function loop(time){const delta=Math.min(.035,(time-last)/1000||0);last=time;if(running&&!paused)update(delta);draw();frame=requestAnimationFrame(loop);}function togglePause(){if(!game||game.completed)return;paused=!paused;document.getElementById('pause').textContent=paused?'Reprendre':'Pause';}
document.addEventListener('keydown',event=>{const dir=keyMap[event.key]||keyMap[event.key.toLowerCase?.()];if(dir){event.preventDefault();requestMove(dir);}if(event.key==='p'||event.key==='Escape')togglePause();});document.querySelectorAll('[data-dir]').forEach(button=>button.addEventListener('pointerdown',event=>{event.preventDefault();requestMove(button.dataset.dir);}));canvas.addEventListener('pointerdown',event=>{const rect=canvas.getBoundingClientRect(),x=event.clientX-rect.left-rect.width/2,y=event.clientY-rect.top-rect.height/2;requestMove(Math.abs(x)>Math.abs(y)?x<0?'left':'right':y<0?'up':'down');});document.getElementById('start').onclick=start;document.getElementById('replay').onclick=start;document.getElementById('pause').onclick=togglePause;
window.TraverseeTestAPI={diagnostics(){const sample=createGame('diagnostic');return{lanes:sample.lanes.length,road:sample.lanes.some(lane=>lane.kind==='road'),river:sample.lanes.some(lane=>lane.kind==='river'),safeRows:sample.lanes.filter(lane=>lane.kind==='safe').length,difficulties:Object.keys(difficulties),goals:[...goalSelect.options].map(option=>option.value),canvas:canvas.width===720&&canvas.height===760};}};
try{localStorage.setItem('game-hub:last-game','traversee-turbo');}catch{}game=createGame('preview');updateHud();draw();frame=requestAnimationFrame(loop);
