'use strict';
const boardElement=document.getElementById('board'),scoreElement=document.getElementById('score'),statusElement=document.getElementById('status'),sizeSelect=document.getElementById('size'),targetSelect=document.getElementById('target');
let size=4,board=[],score=0,history=[],random=Math.random,finished=false,gameIndex=0;
const emptyIndexes=()=>board.map((value,index)=>value? -1:index).filter(index=>index>=0);
function addTile(){const empty=emptyIndexes();if(!empty.length)return;const index=empty[Math.floor(random()*empty.length)];board[index]=random()<.9?2:4}
function start(){size=Number(sizeSelect.value);const sharedSeed=new URLSearchParams(location.search).get('seed');random=window.GameRuntime?.createRandom(`fusion:${sharedSeed||Date.now()}:${sharedSeed?0:gameIndex++}`)||Math.random;board=Array(size*size).fill(0);score=0;history=[];finished=false;window.GameRecords?.reset();addTile();addTile();render()}
function lines(direction){const result=[];for(let outer=0;outer<size;outer++){const line=[];for(let inner=0;inner<size;inner++){const row=direction==='up'?inner:direction==='down'?size-1-inner:outer;const col=direction==='left'?inner:direction==='right'?size-1-inner:outer;line.push(row*size+col)}result.push(line)}return result}
function move(direction){if(finished)return;const before=board.join(',');const snapshot={board:[...board],score};for(const indexes of lines(direction)){const values=indexes.map(index=>board[index]).filter(Boolean);const merged=[];for(let index=0;index<values.length;index++){if(values[index]===values[index+1]){const value=values[index]*2;merged.push(value);score+=value;index++}else merged.push(values[index])}while(merged.length<size)merged.push(0);indexes.forEach((boardIndex,index)=>{board[boardIndex]=merged[index]})}if(board.join(',')===before)return;history.push(snapshot);addTile();const target=Number(targetSelect.value);if(board.some(value=>value>=target)){finished=true;statusElement.textContent=`Objectif ${target.toLocaleString('fr-FR')} atteint !`;window.GameRecords?.finish({score,scoreLabel:`${score} points`,won:true})}else if(!canMove()){finished=true;statusElement.textContent='Plus aucun mouvement possible.';window.GameRecords?.finish({score,scoreLabel:`${score} points`,won:false})}render()}
function canMove(){if(emptyIndexes().length)return true;return board.some((value,index)=>index%size<size-1&&value===board[index+1]||Math.floor(index/size)<size-1&&value===board[index+size])}
function render(){boardElement.style.setProperty('--size',size);boardElement.replaceChildren(...board.map(value=>{const tile=document.createElement('div');tile.className='tile';tile.textContent=value||'';tile.style.setProperty('--level',value?Math.log2(value):0);return tile}));scoreElement.textContent=`Score : ${score}`;document.getElementById('undo').disabled=!history.length}
document.getElementById('newGame').onclick=start;document.getElementById('undo').onclick=()=>{const previous=history.pop();if(previous){board=previous.board;score=previous.score;finished=false;statusElement.textContent='Mouvement annulé.';render()}};sizeSelect.onchange=start;targetSelect.onchange=render;
document.addEventListener('keydown',event=>{if(event.target.matches('select,input,textarea'))return;const map={ArrowUp:'up',z:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',q:'left',a:'left',ArrowRight:'right',d:'right'};const direction=map[event.key];if(direction){event.preventDefault();move(direction)}});document.querySelectorAll('[data-key]').forEach(button=>button.onclick=()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:button.dataset.key})));
start();window.addEventListener('lan:start',start);window.Fusion2048TestAPI={diagnostics:()=>({size,tiles:board.filter(Boolean).length,score,targets:[...targetSelect.options].map(option=>Number(option.value)),movable:canMove()})};
